### ISSUE TITLE
create custom repository for mbeddr plugins

### ISSUE THREAD

**Issue by coolya** [mbeddr/mbeddr.core#1002]
We can use the MPS plugin infrastructure to distribute a mbeddr release to the end users. 

MPS will also update those plugins when we release a new version. Similar to the eclipse update site stuff.

http://blog.jetbrains.com/idea/2008/03/enterprise-plugin-repository/

**Comment by alexanderpann** [comment]
I am closing as this was implemented but removed some time ago because it wasn't used anymore.
