### ISSUE TITLE
Dataflow analysis for return statements

### ISSUE THREAD

**Issue by szabta89** [mbeddr/mbeddr.core#1037]
An error should be reported if the return statement is missing on some branch of the program execution, where the program should clearly return a value. For example, no error is raised in the following scenario:

int16 foo() { 
  for (int16 i = 0; i < 0; i++) { 
    return 44; 
  }
}

**Comment by alexanderpann** [comment]
If I got that correctly, that issue is fixed. An error is shown that a return statement is expected.
