### ISSUE TITLE
Running analyses tests from command line under windows does not work since the classpath is too big

### ISSUE THREAD

**Issue by danielratiu** [mbeddr/mbeddr.core#1045]
Whey trying to run the analyses tests from console under windows, ("ant test-analyses"), java does not start since the total size of all parameters is too big even if put mbeddr and MPS in the root directory.

The problem seems to be the class path that collects ALL jars, most of them not needed by running analyses.

**Comment by alexanderpann** [comment]
I am closing because this issue was fixed quite a while ago. Workaround: choose the option 'compressArgs' in 'test modules' node in the build solution ([MPS-24137](https://youtrack.jetbrains.com/issue/MPS-24137)).
