### ISSUE TITLE
mbeddr versionning

### ISSUE THREAD

**Issue by qutorial** [mbeddr/mbeddr.core#1072]
Mbeddr consists of MPS, plugins for it: spawner, tables, richtext, multiline, math, and mbeddr code itself, plus other tools, like CBMC.

To be able to build a specific version of mbeddr, for example one in a branch called A, one has to make sure, that MPS version and plugins' versions match and are those, requires by a the branch A.

It is currently not possible to obtain matching versions for plug-ins (except of spawner). So if the branch A uses another MPS than the branch Master, it will not compile.

It would be great, if for each branch of mbeddr plugins were built specifically with the corresponding MPS version.

This is done for spawner plugin already, and it has to be done for other plugins.

The code/languages/build.xml file contains the lines:
  <property name="branch.spawner" value="branch:master"/> 
  <property name="branch.tables" value="branch:31_EAP1-25"/> 
  <property name="branch.richtext" value="branch:31_EAP"/> 
  <property name="branch.multiline" value="branch:31_EAP"/>
  <property name="branch.math" value="branch:master"/>
  <property name="branch.bool-editor" value="branch:master"/> 

Where one could select the necessary branch for plug-ins. But different repositories are used for different plugins. 

We have to find a solution to this problem, otherwise the installer will keep breaking each time a new MPS appears, or plugins are not updated with the new MPS version.

This is a version control mess, to which we have to find a good solution.

**Comment by alexanderpann** [comment]
I am closing because this ticket is very outdated.
