### ISSUE TITLE
mbeddr does not work with MPS's IntelliJ Plugin Version

### ISSUE THREAD

**Issue by z9luo** [mbeddr/mbeddr.core#1098]
Mbeddr 6.0 works perfectly on MPS 3.0.3 standalone.  MPS 3.0.3 also works as plugins of IntelliJ 12.1.7. However, when I tried to install mbeddr based on the plugin version of MPS, mbeddr plugins failed to be loaded in IntelliJ.

**Comment by coolya** [comment]
We have no plans to support this use case.
