### ISSUE TITLE
Getting type error when changing a binary operator to -

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#1141]
Somehow, specificially for the "-" operator, the rebinding does not work when changing to it.
To reproduce:
- write an expression like 7 \* 2
- stand on the \* with the cursor
- ctrl-space and change \* to - from the completion list
  Now you will get an error: cannot be applied...
- press F5 to rebind
  Error is gone

All the other operators I tried (+, *, / , %) don't have this issue.

**Comment by alexanderpann** [comment]
Not reproducible anymore.
