### ISSUE TITLE
LLDB not supported

### ISSUE THREAD

**Issue by DomenikP** [mbeddr/mbeddr.core#1147]
Our debugger runtime uses the Eclipse CDT as a debugger backend for communicating with GDB. This debugger backend currently does not support LLDB (Eclipse CDT Luna Service Release 1 (4.4.1). 

The following bug tracks the progress on supporting LLDB in Eclipse CDT:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=405670

**Comment by alexanderpann** [comment]
The debugger was removed in https://github.com/mbeddr/mbeddr.core/pull/2509. The ticket is now obsolete.
