### ISSUE TITLE
Bad rendering of empty table: <no ...> row should span all columns

### ISSUE THREAD

**Issue by vlsi** [mbeddr/mbeddr.core#1181]
See how "<no arguments>" row does not span full row, so the table looks inconsistent:
![screenshot_before_exception](https://cloud.githubusercontent.com/assets/213894/7789346/e2a1c256-0265-11e5-83f7-911382398cda.png)

Table editor: 
![table_editor](https://cloud.githubusercontent.com/assets/213894/7789350/34ec450e-0266-11e5-9586-dbb11c2a8e92.png)

Row editor:
![table_row_editor](https://cloud.githubusercontent.com/assets/213894/7789352/3dd5d3ba-0266-11e5-897e-bf3a4a769477.png)

**Comment by coolya** [comment]
Hi @vlsi,

we have a extra repository for the tables. Would you mind creating the issues over there? Would make them better to track for us.

https://github.com/slisson/mps-tables

**Comment by vlsi** [comment]
Oh, got the idea. Will move there.

**Comment by vlsi** [comment]
Moved to https://github.com/slisson/mps-tables/issues/91
