### ISSUE TITLE
allow unit tests to assert on stdout pattern

### ISSUE THREAD

**Issue by coolya** [mbeddr/mbeddr.core#1191]
Some unit tests, need to check if a certain error message was created respectively stdout/stderr contain some string they are looking for.

We can allow test cases to buffer [stdout/stderr](http://stackoverflow.com/questions/955962/how-to-buffer-stdout-in-memory-and-write-it-from-a-dedicated-thread) or we want to have a special reporting generator that buffers the data printed with `report` statements.

**Comment by bkolb** [comment]
Not sure that helps in your scenario, but a message can be marked to count how often is was issued. A test case can then use that information to check. Was that what you have been looking for?
