### ISSUE TITLE
ToDo Finder

### ISSUE THREAD

**Issue by DomenikP** [mbeddr/mbeddr.core#1192]
The current mbeddr ToDo viewer doesn't work in the current mbeddr master and is therefore disabled for now.

It should be fixed, but also refactored in the following way:
Instead of searching for instances of IIsDocumentationComment, we should rather build a specific ToDoWord concept and search for instances of that.

This change will increase search performance and result in a cleaner solution.

**Comment by alexanderpann** [comment]
I removed the mbeddr TODO finder in #2422 and integrated the old comments the generic MPS way.
