### ISSUE TITLE
Endless loop in liveness analyzer

### ISSUE THREAD

**Issue by slisson** [mbeddr/mbeddr.core#1196]
- I moved some variables from an ImplementationModule to a Component
- I have lots of broken references
- I hit F5 to resolve the references
- MPS hangs and YourKit shows this CPU Usage Estimation:

<img width="1513" alt="screen shot 2015-07-09 at 12 45 05" src="https://cloud.githubusercontent.com/assets/1543361/8593501/8e4dd428-2638-11e5-9364-340366cd8182.png">

**Comment by szabta89** [comment]
fixed with #f0572ee508c558c85aa56febec8aed7ae873767b
