### ISSUE TITLE
Uninitialized read error for component fields

### ISSUE THREAD

**Issue by slisson** [mbeddr/mbeddr.core#1197]
Reading a component field without initializer shows the error "Reading from uninitialized variable ...".
It is initialized in the "on init" runnable, so no error should be shown.

**Comment by stephaneberle9** [comment]
Is this issue still an issue? With the latest mbeddr builds, I don't get this error any longer.

**Comment by alexanderpann** [comment]
Let's close this old ticket and create a new one if the issue still exists.
