### ISSUE TITLE
No way to specify values for instance parameters of composite components

### ISSUE THREAD

**Issue by slisson** [mbeddr/mbeddr.core#1201]
Here I declare the parameters

<img width="953" alt="screen shot 2015-07-10 at 15 17 25" src="https://cloud.githubusercontent.com/assets/1543361/8619357/ceb349c4-2716-11e5-822a-7093198eb34b.png">

but when I instantiate the component, there is no way to define values for the parameters

<img width="269" alt="screen shot 2015-07-10 at 15 19 14" src="https://cloud.githubusercontent.com/assets/1543361/8619393/0f65797e-2717-11e5-95aa-07cf220fab2a.png">

**Comment by bkolb** [comment]
this is not the way it is supposed to work.

you have to declare the parameters as fields in the component and then pass them into the instance config (e.g. in the setup runnable).

But I agree that this could be improved

**Comment by markusvoelter** [comment]
Why is it possible to specifiy parameters for "internal instances" in the
first place?
​

**Comment by bkolb** [comment]
Because you may want to do some calculations in the setup runnable and then pass those into the initialize instances
