### ISSUE TITLE
DecTab: Nodes in "cExpr" are not deleted after deleting a row/column

### ISSUE THREAD

**Issue by slisson** [mbeddr/mbeddr.core#1204]

**Comment by bkolb** [comment]
A delete handler is implemented, but seems to not be called. Can you please check?
http://localhost:8080/select/com.mbeddr.core/r:2003a7dc-1d33-4109-abf0-90ad1f9028fd/7133464512081414204/

**Comment by alexanderpann** [comment]
Not reproducible anymore, seems to be fixed.
