### ISSUE TITLE
StringType in InterpreterConstraintExpression produces non compilable java code

### ISSUE THREAD

**Issue by joao-silveira** [mbeddr/mbeddr.core#1211]
Hi all,

There seems to be an issue with mbeddr interpreter code generator,

I´ve noticed that when your InterpreterConstraintExpression is of StringType this will result in non compilable java code. This seems to happen because in InterpretConstraintException reduction rule there is the following implementation:

(outputNode, genContext, operationContext, node)->join(node<Classifier> | string) { 
  node<> type = node.type; 
  if (type.isInstanceOf(PrimitiveType)) { 
    return ((node<PrimitiveType>) type).getBoxedType().getDetailedPresentation(); 
  } else { 
    return type.getDetailedPresentation(); 
  } 
}

As 'StringType" is not an instance of 'PrimitiveType' it will rely on the getDetailedPresentation returning 'string' instead of the expected java type 'String'.

For now, and as a workaround I found out that just using the java 'String' in your interpreter instead of MPS 'string' works just fine.

Best regards, 
Joao

**Comment by alexanderpann** [comment]
I am closing because the interpreter implementation changed in this is not an issue anymore.
