### ISSUE TITLE
Unintuitive generation from foreach statements

### ISSUE THREAD

**Issue by danielratiu** [mbeddr/mbeddr.core#1228]
the following statement is intended to initialize an array

foreach (clauses sized 10 as it) { it.clauseActive = true; }

... however, in the generated C code, we have:

for ( uint8_t __c = 0 ; __c < 10; __c++ )
  {
    clause_data_structure_clause_t_t __it = clause_data_structure_clauses[__c];
    __it.clauseActive = true;
  }

... thereby the assignment "it.clauseActive = true" is assigned to a temporary variable. ALL occurences of "it" on a left-hand-side of an assignment are thereby DOOMED

**Comment by markusvoelter** [comment]
Which foreach is this? The one from the tutorial?

**Comment by danielratiu** [comment]
no, it is the one from mbeddr

core.util.ForEachStatement

**Comment by markusvoelter** [comment]
So I will change this to:

for ( uint8_t __c = 0 ; __c < 10; __c++ ) {
clause_data_structure_clause_t_t* __it = &clause_data_structure_clauses[__c];
(*__it).clauseActive = true;
}

**Comment by danielratiu** [comment]
ok, this should do it

**Comment by markusvoelter** [comment]
Fixed.
