### ISSUE TITLE
AnonymousUnionDeclaration cannot be instantiated

### ISSUE THREAD

**Issue by danielratiu** [mbeddr/mbeddr.core#1230]
due to: can be child: "parentNode.ancestor\<concept = ExternalModule\>.isNotNull;"

**Comment by danielratiu** [comment]
@bkolb I've talked with Kolja and we "agreed" to remove that constraint - I am closing then this issue

**Comment by danielratiu** [comment]
hmmm - when I removed the constraint the difference between this and StructDeclaration is not clear anymore

**Comment by coolya** [comment]
I think this is fixed since @szabta89 and I did a general overhaul on this.
