### ISSUE TITLE
ProjectionModeSwitcher - more active options in one time

### ISSUE THREAD

**Issue by josefmueller** [mbeddr/mbeddr.core#1231]
ProjectionModeSwitcher (com.mbeddr.mpsutil.refactoring) doesn't work properly to me. Sometimes (not always), it allows multiple options to be selected:

![projectionmodeswitcher](https://cloud.githubusercontent.com/assets/15520928/11183575/bd6d2b14-8c72-11e5-9cf2-abaa10b6dd84.jpg)

The oldest one is always the active one. I have to un-click the old ones to make the new one active.

![image](https://cloud.githubusercontent.com/assets/15520928/11183690/9f33c058-8c73-11e5-91d9-6dc1e575869e.png)

**Comment by alexanderpann** [comment]
That issue seems to be related to #1876 which is fixed.
