### ISSUE TITLE
How can I change the size of a shape

### ISSUE THREAD

**Issue by markusvoelter** [mbeddr/mbeddr.core#1254]
Right now, they seem to have a fixed size (see outer ports in IETS3 component diagrams).

**Comment by slisson** [comment]
project: mps-sl-all (/Users/slisson/mps/mbeddr.core/code/plugins/sl-all)
module:  de.itemis.mps.editor.diagram.demolang
model:   de.itemis.mps.editor.diagram.demolang.editor
root:    ComponentReference_Editor [ConceptEditorDeclaration]
node:    layout [MigLayoutCell]
url:     http://localhost:8080/select/mps-sl-all/r:a9837982-6265-4b61-bb69-6b7c44fb5320/500099795021628347/
