### ISSUE TITLE
Mac RCP

### ISSUE THREAD

**Issue by bkolb** [mbeddr/mbeddr.core#1288]
- [ ] symlink for Contents/bin/libbreakgen.dylib
- [ ] symlink for Contents/bin/libbreakgen64.dylib
- [ ] symlink for Contents/jre/jdk/Contents/Home/jre/lib/jli/libjli.dylib
- [ ] fileWatcher not working
- [ ] fix Info.plist: jvm 1.6+ and         <key>idea.java.redist</key> --> <string>custom-jdk-bundled</string>
- [ ] sign

**Comment by coolya** [comment]
seems done, right?

**Comment by bkolb** [comment]
yes
