### ISSUE TITLE
Bundle com.mbeddr.build

### ISSUE THREAD

**Issue by bkolb** [mbeddr/mbeddr.core#1289]
The tutorial is currently red because of the missing dependency to com.mbeddr.build

**Comment by bkolb** [comment]
the build solution was added to the all-in-one distribution

**Comment by coolya** [comment]
This *will*  break in the RCP that does not allow language development because it is not shipping the build languages.

**Comment by bkolb** [comment]
Isn't it that just that plugin will not be loaded?

**Comment by bkolb** [comment]
The only thing I've done is
* adding it to the all-in-one.zip
* adding it to the new all-in-one plugin
