### ISSUE TITLE
Build bootstrapping problem

### ISSUE THREAD

**Issue by coolya** [mbeddr/mbeddr.core#1291]
If mbeddr war not successfully build once no spawner is present in MPS nor can the `copy-spawner` ant task be executed successfully. This is quite a problem when updating MPS and the mbeddr build breaks because in the IDE everything is red cause of missing spawner plugin.

**Comment by alexanderpann** [comment]
This ticket is deprecated, especially with the plans to remove the spawner: https://github.com/mbeddr/mbeddr.core/pull/2272
