### ISSUE TITLE
Diagram: Add padding for boxes on auto-size

### ISSUE THREAD

**Issue by slisson** [mbeddr/mbeddr.core#1304]
If the shape is not a rectangle, then you might need some extra space to keep the content cell inside the shape.

<img width="98" alt="screen shot 2016-02-15 at 11 30 51" src="https://cloud.githubusercontent.com/assets/1543361/13046235/efdece48-d3d7-11e5-8c25-945ea9530d2a.png">

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/89)
