### ISSUE TITLE
Constant-Only "optional" cell: output error

### ISSUE THREAD

**Issue by markusvoelter** [mbeddr/mbeddr.core#1307]
If users create a grammar.optional cell and only put a constant into it (because they forgot to put a list around constant + the optional element) then the generator fails. Since having only a constant in the optional cell is never useful, please report and error in this case.

**Comment by alexanderpann** [comment]
I am closing this ticket because, although we don't have a check in the editor, the generator clearly shows the message: `rule dismissed: Content of optional cell is not supported`
