### ISSUE TITLE
module com.mbeddr.mpsutil.actionsfilter.runtime not available in platform-distribution

### ISSUE THREAD

**Issue by 4gitHubMe** [mbeddr/mbeddr.core#1308]
Using concept "ActionsProfile" fails with platform-distribution from 15.02.16 (and earlier), also indicated during MPS project loading:
quote: "WARN - lassloading.ClassLoadersHolder - Facet of the module com.mbeddr.mpsutil.actionsfilter.runtime [solution] is not valid -- possibly the provided idea plugin (in the properties dialog/idea plugin facet tab) cannot be found among the bundled plugins"

**Comment by alexanderpann** [comment]
As the error message correctly describes, the idea plugin `com.mbeddr.mpsutil.actionsfilter` that should be part of the platform distribution must be installed in the plugins folder for the actions filter language to work.
