### ISSUE TITLE
"New Root" menu

### ISSUE THREAD

**Issue by markusvoelter** [mbeddr/mbeddr.core#1313]
The upper part of the New Root menu that uses the explicilty-stated categories should also take into account MbeddrIDERoots that are imported via a language, and not via a devkit. In the lower part, the current, devkit-based functionality shall be retained.

**Comment by wsafonov** [comment]
Adjusted handling of MbeddrIDERoots from language imports as requested. Also any MbeddrIDERoots that does not (yet) provide a category string, will be added to the "Other" category which is always displayed at the end of the category menu group.
