### ISSUE TITLE
ProjectView: Show VCS status on nodes

### ISSUE THREAD

**Issue by enikao** [mbeddr/mbeddr.core#1329]
format text as green, blue, (red), if the node is new, changed, (deleted).

**Comment by slisson** [comment]
@coolya are you working this already?

**Comment by coolya** [comment]
There is no API for that, JetBrain will provide some in 3.4

**Comment by coolya** [comment]
Upstream issues is MPS-23491

**Comment by slisson** [comment]
Is that what we need?
`FileStatusManager.getInstance(project).getStatus(MPSNodesVirtualFileSystem.getInstance().getFileFor(node))`

**Comment by coolya** [comment]
I'm not sure. I talked to Alex about it and he said that there is no API for that. But if that works would be great.

**Comment by slisson** [comment]
I found a way. I will implement that. (TreeHighlighterFactory)

**Comment by coolya** [comment]
:+1:
