### ISSUE TITLE
mbeddr plugins not compatible with MPS 3.3.4

### ISSUE THREAD

**Issue by fac2003** [mbeddr/mbeddr.core#1330]
Not sure if this issue has a better home (mps-all perhaps?).

Trying to update to MPS 3.3.4, but the mbeddr plugins (obtained with the mbeddr plugin manager) are not compatible with this build:
Message indicates plugin mps.all is not compatible with MPS installation.

**Comment by slisson** [comment]
I updated the repository. Should work now.

**Comment by fac2003** [comment]
It's working now. Thank you.
