### ISSUE TITLE
Variable usage in convert expression is not recognized

### ISSUE THREAD

**Issue by JanMosigItemis** [mbeddr/mbeddr.core#1337]
![image](https://cloud.githubusercontent.com/assets/16935994/14322815/6ffbb49c-fc1e-11e5-8b03-ad00f2043e1e.png)

The variable `thousandSixHundredMeters` is used in a convert expression only. However there appears a warning saying that the variable is unused.

@DomenikP suggested that the convert expression is missing a data flow builder.

**Comment by szabta89** [comment]
@JanMosigItemis yes! go for it and add it please.

**Comment by JanMosigItemis** [comment]
This issue has been "accidentally" fixed with fd92df2c8b6379dba881052ece82a4c24f5340e0.
