### ISSUE TITLE
UI: Breadcrumb duplicates when displaying Documentation nodes with embedded models

### ISSUE THREAD

**Issue by JanMosigItemis** [mbeddr/mbeddr.core#1342]
When viewing Documentation (D) nodes that contain embedded models, the breadcrumb menu holds multiple identical entries. See the attached image for details.

![image](https://cloud.githubusercontent.com/assets/16935994/14454173/53e3fa2e-0099-11e6-8749-a815625cb3a3.png)

**Comment by alexanderpann** [comment]
Closing because deprecated  breadcrumb language was removed in https://github.com/mbeddr/mbeddr.core/pull/2195.
