### ISSUE TITLE
Argument_Editor: Argument names which contain keywords are not accepted

### ISSUE THREAD

**Issue by JanMosigItemis** [mbeddr/mbeddr.core#1343]
When specifying nodes which take arguments (like functions), the argument name is only partially accepted if it contains keywords like "for". Although it is possible to write out the name, parts of it are rendered in red but no error is indicated whatsoever.

In code completion menus only the "valid" part of the name appears. Calling the function works as expected.

![image](https://cloud.githubusercontent.com/assets/16935994/14454461/fc831790-009a-11e6-90ed-1196fa423fad.png)

Assumption: There is something wrong with the editor of the Argument concept.

Workaround: Write the name while leaving out one character. Add the character in a second step. Or chose another name.

**Comment by alexanderpann** [comment]
Not reproducible anymore. The name is only red if you type exactly "for". In this case, the argument has the last valid name "fo".
