### ISSUE TITLE
Generation bug in mbeddr.core in presence of inlined functions

### ISSUE THREAD

**Issue by danielratiu** [mbeddr/mbeddr.core#1356]
I have two implementation models: m1 contains an inlined function 'boo'; and a module m2 which contains a function 'foo' which calls 'boo'. The module m1 is marked as reexported.

The code generation fails.

![image](https://cloud.githubusercontent.com/assets/1437141/15448147/86672910-1f59-11e6-89cd-da1e732091cf.png)

![image](https://cloud.githubusercontent.com/assets/1437141/15448148/981b0e38-1f59-11e6-947b-a8fe68cf41e4.png)

![image](https://cloud.githubusercontent.com/assets/1437141/15448152/bb02a262-1f59-11e6-99ca-3dc2dba2d208.png)

[inline_bug.zip](https://github.com/mbeddr/mbeddr.core/files/275841/inline_bug.zip)

**Comment by danielratiu** [comment]
here is the error message:

![image](https://cloud.githubusercontent.com/assets/1437141/15448165/6360378a-1f5a-11e6-84f5-19ffcc4be40c.png)

**Comment by bkolb** [comment]
@stephaneberle9 can you please have a look at that? i think you reworked that, right?

**Comment by coolya** [comment]
fixed
