### ISSUE TITLE
Cannot enter empty string literal in mbeddr

### ISSUE THREAD

**Issue by danielratiu** [mbeddr/mbeddr.core#1378]
I cannot write:

string emptyString = "";

**Comment by bkolb** [comment]
you mean because of the <no value>? >

This is just an editor thing. I fix it. But what would you do with an empty string in C?

**Comment by danielratiu** [comment]
@bkolb I encountered this in imported code like the following:

char* stringPrefix = cond ? "~" : "";

thanks for the fix ...
