### ISSUE TITLE
mbeddr "New model" action hangs up MPS

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#1401]
Using MPS 3.3.5 with mbeddr-nightly94

When making a new model using the "New model" action from the context menu (see picture)
![image](https://cloud.githubusercontent.com/assets/6429350/16191538/06c27072-36e5-11e6-8002-683915370c2f.png)

I give model name and press OK (see picture)
![image](https://cloud.githubusercontent.com/assets/6429350/16191582/3cb9d102-36e5-11e6-8a01-62a3b6392034.png)

and MPS hangs up in the "Model properties" dialog (see picture)
![image](https://cloud.githubusercontent.com/assets/6429350/16191646/9ea1ba10-36e5-11e6-9da0-20253c10f501.png)

The only way I found to get out of this is to kill the javaw process to kill all of MPS. When restarting, the model is there (with default properties set), so nothing seems to be broken.

Would it be possible to find out why this hang happens and prevent it from happening? Thanks!

**Comment by coolya** [comment]
Its fixed in #1381
