### ISSUE TITLE
allow to initialise structs with zero

### ISSUE THREAD

**Issue by coolya** [mbeddr/mbeddr.core#1403]
This is valid C code:

`softap_configconfig = { 0 };`

which will zero out the memory of the struct. 

C99 Standard 6.7.8.21:

> If there are fewer initializers in a brace-enclosed list than there are elements or members of an aggregate, or fewer characters in a string literal used to initialize an array of known size than there are elements in the array, the remainder of the aggregate shall be initialized implicitly the same as objects that have static storage duration.

We should also allow that in mbeddr because for large structs it safes a lot of typing.

**Comment by alexanderpann** [comment]
That seems to work and I can see even [tests](http://127.0.0.1:63320/node?ref=r%3A0c020a2a-0fae-4359-90ba-63fdf45caa94%28tests.ts.core.tests1%40tests%29%2F3073566081777350308) where this worked a year before. Please reopen if I misinterpreted the missing functionality.
