### ISSUE TITLE
Support for curves for diagram editor edges

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#1404]
Would it be possible to make the diagram editor use smooth curves (e.g. bezier curves) for the edge style instead of only curves with sharp corners?

**Comment by slisson** [comment]
In the editor of the edge you can set "curved" to true. This feature was added about a month ago.
If your mbeddr version is older, get a new one from here: https://github.com/mbeddr/mbeddr.core/releases
