### ISSUE TITLE
Breadcrumbs always appear in multiple of 4

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#1405]
When opening an mbeddr model that is written in the documentation language, I see the breadcrumbs in 4-fold (see picture):
![image](https://cloud.githubusercontent.com/assets/6429350/16364679/56f32dc2-3bed-11e6-9bae-2987232b04ff.png)
I think this should be only onefold. Is it possible to remove the other 3 exactly the same breadcrumb lines?

**Comment by alexanderpann** [comment]
Closing because deprecated breadcrumbs language was removed in https://github.com/mbeddr/mbeddr.core/pull/2195.
