### ISSUE TITLE
Subdiagrams are outside their box after autolayout and zoom

### ISSUE THREAD

**Issue by slisson** [mbeddr/mbeddr.core#1411]
![pasted image at 2016_06_29 04_40 pm](https://cloud.githubusercontent.com/assets/1543361/16457004/4d2e9aea-3e1a-11e6-8c26-6d73f65f7c77.png)

"This happed after I pressed the +, - and auti-layout buttons a few times.
When I click on the empty grey box,  the contents suddenly jumps into it again"

**Comment by slisson** [comment]
Similar to #1467

**Comment by slisson** [comment]
Also the subdiagram do not fill the box

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/90)
