### ISSUE TITLE
Statemachine Diagram: Duplicate connection types when a new connection is created

### ISSUE THREAD

**Issue by slisson** [mbeddr/mbeddr.core#1412]
![pasted image at 2016_06_29 05_00 pm](https://cloud.githubusercontent.com/assets/1543361/16457317/492d07fa-3e1b-11e6-8ca2-50dd4a4fd8a2.png)

**Comment by alexanderpann** [comment]
I am closing because this issue was fixed in https://github.com/mbeddr/mbeddr.core/commit/78f7387fc6464e86d8266520fd496dafad3be78e and https://github.com/mbeddr/mbeddr.core/commit/639c3b759a551f3a5d50d06b48549997b0f163ab.
