### ISSUE TITLE
1.0 Release notes

### ISSUE THREAD

**Issue by coolya** [mbeddr/mbeddr.core#1415]
Please add your release notes here.

Todo:
- [ ] 1.0 version number on plugins

**Comment by danielratiu** [comment]
- Functional verification and robustness checks using the CBMC model checker
- Checking the consistency of variability definition and use

**Comment by coolya** [comment]
- new export logic (header/reexport)

**Comment by alexanderpann** [comment]
This ticket is obsolete.
