### ISSUE TITLE
Deleting a node reference in diagram editor reinstitues old reference instead of deleting it

### ISSUE THREAD

**Issue by joswarmer** [mbeddr/mbeddr.core#1417]
Step 1: reference to AtomicA in graphical editor
Step 2: select AtomicA text
Step 3: press DEL ==> you see <no name>
Step 4: press DEL again ==> AtomicA appears again,  it should become <no block>

Doing the same in the textual editor will show <no block> in step 4
![1](https://cloud.githubusercontent.com/assets/818164/16565723/7843a7a4-420f-11e6-8b53-ee5726a9e938.PNG)
![2](https://cloud.githubusercontent.com/assets/818164/16565724/7a237cac-420f-11e6-851e-021f38932529.PNG)
![3](https://cloud.githubusercontent.com/assets/818164/16565726/7c1a6a0c-420f-11e6-8411-139b06342177.PNG)
![4](https://cloud.githubusercontent.com/assets/818164/16565729/7ded3b20-420f-11e6-915d-b3ab26b13c3e.PNG)

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/83)
