### ISSUE TITLE
Text within diagram box does not always update in time

### ISSUE THREAD

**Issue by joswarmer** [mbeddr/mbeddr.core#1418]
1, I have a box with a reference to a Block (update-1)
2. I select the referred name (update-2)
3. I press DEL (update-3)
4. I press DEL again => Still see update-3  (**incorrect**)
5. I select anything else in the diagram (or outside) and I get update-4, which I shiould already get in step 4
6. I go into the box and get the code completion (update-5)
7. I select the element in the menu => still see update-5 (**incorrect**)
8. I select anything else and get update-6, which I should get at step 7
![update-1](https://cloud.githubusercontent.com/assets/818164/16613901/bc934b84-436e-11e6-8c05-8b320d3aa9dc.PNG)
![update-2](https://cloud.githubusercontent.com/assets/818164/16613905/c191be4a-436e-11e6-93be-fabe31c96a92.PNG)
![update-3](https://cloud.githubusercontent.com/assets/818164/16613910/c7261450-436e-11e6-8905-6c1acf3b5154.PNG)
![update-4](https://cloud.githubusercontent.com/assets/818164/16613911/c8e53e1a-436e-11e6-951a-8f39691ebdb8.PNG)
![update-5](https://cloud.githubusercontent.com/assets/818164/16613915/cac4fd7e-436e-11e6-8c9d-d30d5016b02c.PNG)
![update-6](https://cloud.githubusercontent.com/assets/818164/16613918/cc094f1e-436e-11e6-9588-1429ca574578.PNG)

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/84)
