### ISSUE TITLE
Running tests from the command line with MPS open cause exception

### ISSUE THREAD

**Issue by ftomassetti** [mbeddr/mbeddr.core#1420]
The exception is about the address for the internal server being already in use.
Would it be possible to either:
1. Check if the port is free before starting the server
2. Specify as a configuration parameter the port to be used for tests

**Comment by coolya** [comment]
Whats the problem here? Do the tests stop because of this? I don't think so. I think there is no quick workaround.

**Comment by ftomassetti** [comment]
No, it is not making the tests fail (at least not the one not depending on the internal server). However it is distracting. In general these exceptions are most of time not the symptom of an issue but they could possibly hide an issue. In this sense it would be cool to remove them. For example if running the test I could pass an environment variable which overrides the HTTP port to be used that would solve the issue I think.

**Comment by coolya** [comment]
Seems like a good idea. We will introduce  a environment variable that has priority over the settings.
