### ISSUE TITLE
When cloning a model with a graphical editor, layout is not preserved

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#1421]
Steps to reproduce:
-Make a model with a graphical editor in it
-Layout the model manually
-Clone the model

Result: the layout in the cloned model is completely lost with respect to the original model

Some ideas:
-why is the layout not part of the model contents? is that a conscious choice?
-in how far can layout be seen as something with meaning?
-is it necessary to force the user to auto-layout or is the layout also seen as something that adds hints to understand the model?

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/86)
