### ISSUE TITLE
Diagram: Loop edges cannot be layouted

### ISSUE THREAD

**Issue by slisson** [mbeddr/mbeddr.core#1424]
Edges with the same source and target are not layouted by the libavoid layouter. Also it is not possible to manually layout these edges, when they have no bend points, because their size is then 0.

**Comment by enikao** [comment]
This may happen if the edges are created by a query, and the query returns more edges now compared to the point in time when the node was first dragged on the canvas.

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/73)
