### ISSUE TITLE
Binary is only present on every second rebuild

### ISSUE THREAD

**Issue by coolya** [mbeddr/mbeddr.core#1425]
Rebuild model -> executable there -> rebuild model -> executable gone -> rebuild model -> executable there -> etc

**Comment by slisson** [comment]
Is the reason, that the output of the compiler is put into the source_gen folder? I have the same problem with the typescript compiler.

**Comment by coolya** [comment]
Yes thats the problem. The delta builder in the make facet seems to delete the files.

**Comment by coolya** [comment]
Fixed with the changes from @szabta89  in 0b011bb945e67b2b1374eef48a0a7de5d43d5dee
