### ISSUE TITLE
Colors in diagram editor definition not legible

### ISSUE THREAD

**Issue by joswarmer** [mbeddr/mbeddr.core#1428]
In the diagram definition the background color of "diagram" and "diagram box" etc .  is dark grey,  and the foreground color is purple. I cannot read this as the contrast between the colors is not high enough.
Solution: change background color to e.g. white.

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/74)
