### ISSUE TITLE
The value of CBMC_CMD environment variable under windows is in quotes

### ISSUE THREAD

**Issue by danielratiu** [mbeddr/mbeddr.core#1435]
please see the picture attached

![image](https://cloud.githubusercontent.com/assets/1437141/16897207/eec36582-4baa-11e6-87b6-435220fe9417.png)

now it is:
CBMC_CMD="d:\tools\cbmc.exe"

it should be without quotes:
CBMC_CMD=d:\tools\cbmc.exe

**Comment by bkolb** [comment]
Is this a problem? The reason for the quotes is that the path might contain whitespaces...

**Comment by danielratiu** [comment]
under Windows all environment variables are *without* quotes

**Comment by bkolb** [comment]
i removed the quotes. we have to check if it still works now, even if the path contains whitespaces. otherwise we have to add them when calling cbmc
