### ISSUE TITLE
GSwitchExpression and DecTabs inside a ForEachStatement and ForRangeStatement fails to generate

### ISSUE THREAD

**Issue by danielratiu** [mbeddr/mbeddr.core#1443]
I am trying to use a GSwitchExpression and DecTab as shown below and the generator throws errors

![image](https://cloud.githubusercontent.com/assets/1437141/17086576/6a135e12-51f6-11e6-852f-b380f264fe65.png)

![image](https://cloud.githubusercontent.com/assets/1437141/17086582/80d6587a-51f6-11e6-8b63-a2c43fe3ba8b.png)

![image](https://cloud.githubusercontent.com/assets/1437141/17086592/a7537686-51f6-11e6-953a-6ba3cec9c016.png)

![image](https://cloud.githubusercontent.com/assets/1437141/17086595/c0d44752-51f6-11e6-923c-446f465f6feb.png)

![image](https://cloud.githubusercontent.com/assets/1437141/17086608/093a0108-51f7-11e6-989f-c39facc97ee4.png)

![image](https://cloud.githubusercontent.com/assets/1437141/17086611/1d8dec00-51f7-11e6-8270-567b6097252b.png)

**Comment by DomenikP** [comment]
fixed with 779ed94bff77ef59bf694761abc0b36e28c8109e
