### ISSUE TITLE
GSwitch fails to generate when a pointer to an array is used as part of a condition expression

### ISSUE THREAD

**Issue by danielratiu** [mbeddr/mbeddr.core#1444]
![image](https://cloud.githubusercontent.com/assets/1437141/17086745/91aad582-51fa-11e6-8aad-e9f145ad33d8.png)

![image](https://cloud.githubusercontent.com/assets/1437141/17086748/a17eabbe-51fa-11e6-950c-32d691f05d3d.png)

**Comment by coolya** [comment]
For 1.0 I will prohibit the usage of pointers in there. There are to many edge cases that aren't covered.

**Comment by DomenikP** [comment]
fixed with 779ed94bff77ef59bf694761abc0b36e28c8109e
