### ISSUE TITLE
Clicking a reference to a node that is rendered as an edge in a graphical editor, doesn't select this edge in the diagram of the graphical editor

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#1445]
If I make a reference to a node that has a diagram.box as editor, then I can click this reference and the box will be selected in the editor.
If I do the same with a reference to a node that has a diagram.edge as editor, then this edge doesn't get selected.

**Comment by alexanderpann** [comment]
Issue moved to https://github.com/JetBrains/MPS-extensions/issues/583.
