### ISSUE TITLE
Drag & Drop features for the graphical editor

### ISSUE THREAD

**Issue by coolya** [mbeddr/mbeddr.core#1446]
- [x] dropping in nested diagrams should be supported
- [x]  low level Drag and Drop API (source and target with transferable)
- [x]  multiple boxes can't be dropped
- [x]  handler code in editor definition
- [x]  target decides if it can handle the source
- [x]  no Drag & Drop support inside the diagram or between diagrams, only palette  to box
- [x]  highlight the current selected diagram
- [x]  palette is filled based on selected diagram
- [x]  drop support for boxes and edges
- [x]  no drop support for ports
- [x]  feedback to the user if the thing can be dropped at the current location

**Comment by slisson** [comment]
Highlighting of the active diagram: 30ada705f6627ef56432d97f992b4c4e24affe21

**Comment by slisson** [comment]
Doesn't work on windows.

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/75)
