### ISSUE TITLE
Using GSwitchExpressions or DecTabs within the body of a lambda leads to badly generated code

### ISSUE THREAD

**Issue by danielratiu** [mbeddr/mbeddr.core#1448]
![image](https://cloud.githubusercontent.com/assets/1437141/17106506/ef207d8e-528b-11e6-90fe-2973193323b8.png)

![image](https://cloud.githubusercontent.com/assets/1437141/17106531/01bc8456-528c-11e6-961d-f2d3d68658a3.png)

**Comment by DomenikP** [comment]
fixed with 779ed94bff77ef59bf694761abc0b36e28c8109e
