### ISSUE TITLE
GSwitchExpression and DecTabs do not work inside of macros

### ISSUE THREAD

**Issue by danielratiu** [mbeddr/mbeddr.core#1449]
![image](https://cloud.githubusercontent.com/assets/1437141/17133024/916b6b7e-5324-11e6-9734-7e3a5bad2338.png)

![image](https://cloud.githubusercontent.com/assets/1437141/17133043/a466608a-5324-11e6-9e3b-db10bda33847.png)

**Comment by DomenikP** [comment]
fixed with 779ed94bff77ef59bf694761abc0b36e28c8109e
