### ISSUE TITLE
Closures which access local variables lead to compilation error

### ISSUE THREAD

**Issue by danielratiu** [mbeddr/mbeddr.core#1450]
![image](https://cloud.githubusercontent.com/assets/1437141/17156822/0b5143b6-538c-11e6-961f-32df2eddd052.png)

![image](https://cloud.githubusercontent.com/assets/1437141/17156842/26e08c90-538c-11e6-9f21-c062c710e154.png)

**Comment by DomenikP** [comment]
fixed with 779ed94bff77ef59bf694761abc0b36e28c8109e
