### ISSUE TITLE
[exported reexport] The exported property should require corresponding imported modules to be reexported

### ISSUE THREAD

**Issue by ksun-x** [mbeddr/mbeddr.core#1453]
For instance, an implementation module `myModule` has an **exported** enum declaration, which uses a constant `myConstant` defined in a **non-reexported** imported module `myLib`. In current version, no error like `must be reexported` is reported. 

After generation, the enum declaration is located in the generated header file `myModule.h` while `#include "myLib.h"` is in `myModule.c`. Hence an error `myConstant undeclared here` would be thrown during make.

**Comment by ksun-x** [comment]
One more concrete case:

In the `com.itemis.embedded.platform.raspi.advaboardrpi1.implementation.impl.AbstractDigitalIOPinImpl` module, the `configurePin` runnable has a parameter `ioConfig` whose type is an enum `am_config_io`. This enum is declared in an imported module `am_rpi_advaboard`.

When `am_rpi_advaboard` is **non-reexported**, no error is reported. However, when this module is rebuilt in the model `com.itemis.embedded.platform.examples.towerofhanoi.integrations.advaboardrpi1.win32.io`, an error is reported to indicate that `#include <am_rpi_advaboard.h>` should be located in `AbstractDigitalIOPinImpl.h` rather than in `AbstractDigitalIOPinImpl.c`. 

To avoid this case, `am_rpi_advaboard` should be checked whether it **`must be reexported`**.

**Comment by alexanderpann** [comment]
Closing because seems to be fixed in https://github.com/mbeddr/mbeddr.core/pull/1699.
