### ISSUE TITLE
Table editor (d.s.m.tables) doesn't show column headers and row headers parts

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#1454]
When I make a new table editor and I compare that with, e.g. the statemachines table editor, then the column headers and row headers parts are missing, only the cells part is visible.
I think this has to do with a bug in the Table editor condition to show these parts (see image): 
![image](https://cloud.githubusercontent.com/assets/6429350/17180847/12ffe012-541e-11e6-8536-09ca7eb4d808.png)

**Comment by alexanderpann** [comment]
I am closing because column and row headers are now deprecated and this is the expected behavior. They are only shown now for compatibility reasons.
