### ISSUE TITLE
Should be able to adjust spacing/padding of box contents.

### ISSUE THREAD

**Issue by joswarmer** [mbeddr/mbeddr.core#1456]
The content of a box (i.e. a text editor) is very close to the box border.  This distance is fixed currently.  I would like to be able to specify a "margin" that states the amount of space between the box border and its contents.

**Comment by joswarmer** [comment]
There should be separate top, bottom, left and right margins.  If there are, #1464 will be resolved as well.

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/78)
