### ISSUE TITLE
Diagram: Allow shapes to reserve additional space

### ISSUE THREAD

**Issue by slisson** [mbeddr/mbeddr.core#1464]

**Comment by joswarmer** [comment]
Need this for ESD.

**Comment by joswarmer** [comment]
I think this will be resolved if #1456 has been fixed.

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/79)
