### ISSUE TITLE
Borders inside boxes don't work correctly.

### ISSUE THREAD

**Issue by joswarmer** [mbeddr/mbeddr.core#1466]
Using a border inside a box does not work correctly.
- The border does not display when the box is filled. 
- If the box is not filled,m it displays at the wrong location. 

See the following picture, the box is defined around the text and shows at the incorrect location:
![border-incorrect-in-box](https://cloud.githubusercontent.com/assets/818164/17406831/575c34ca-5a65-11e6-921a-991cb399cc17.PNG)

The same editor not in a box is ok:
![box-ok](https://cloud.githubusercontent.com/assets/818164/17406836/608311ae-5a65-11e6-8228-80ab1d2b446c.PNG)

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/81)
