### ISSUE TITLE
Auto layout option moves the contents of boxes (it should not)

### ISSUE THREAD

**Issue by joswarmer** [mbeddr/mbeddr.core#1467]
First click on "Fit size of All Boxes".   Then click on "Auto Layout Diagram".  The Auto layout action then changes the location of the contents inside the boxes in the diagram.  I was expecting that it would only re-layout the boxes, not their contents.

If I select a box after the re-layout, the box gets selected and its contents immediately moves back to the position after the "Fix Size of All boxes".  My guess is that the move of the contents after the re-layout is probably wrong.

**Comment by joswarmer** [comment]
Sometimes, :Fix size of all boxes" does not restore the position of the internal contents of a box,  only selecting the box does.

**Comment by joswarmer** [comment]
Ans sometimes selecting does not restore the position,  I first need to drag the box.

**Comment by joswarmer** [comment]
Sometimes I just have to select one box and all contents of all boxes in the diagram move to the correct position at once!

**Comment by slisson** [comment]
Similar to #1411

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/82)
