### ISSUE TITLE
Support optional grammar cell in optional grammar cell

### ISSUE THREAD

**Issue by szabta89** [mbeddr/mbeddr.core#1468]
Currently compilation of such editor definition fails.

**Comment by slisson** [comment]
It works for this test case: <img width="662" alt="screen shot 2016-08-29 at 10 04 34" src="https://cloud.githubusercontent.com/assets/1543361/18044844/0bde5234-6dd0-11e6-97b3-dad95df002a8.png">

How does your editor look like?

**Comment by alexanderpann** [comment]
I am closing this issue because no further feedback was provided and the current implementation of the optional cells differs so much from this old implementation that the report is not relevant anymore.
