### ISSUE TITLE
Code generated for "if" in shape property results in cast error

### ISSUE THREAD

**Issue by joswarmer** [mbeddr/mbeddr.core#1469]
When I use the if in the shape property to check for node type as in:

![if-code-in-shape-property](https://cloud.githubusercontent.com/assets/818164/17583997/4cb66456-5fb4-11e6-87d0-006e5ae229e9.PNG)

The generated code performs the cast before the if is evaluated, resulting in a Java cast error at runtime:
![generated-code](https://cloud.githubusercontent.com/assets/818164/17584013/657ec992-5fb4-11e6-8e31-497a2202f626.PNG)

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/64)
