### ISSUE TITLE
Allow nodes to be visible in multiple diagrams

### ISSUE THREAD

**Issue by joswarmer** [mbeddr/mbeddr.core#1470]
A node is often visible in multiple diagrams. E.g. when inherited nodes are shown somewhere in an extends hierarchy.  Currently you cannot use the _nodesQuery_ to get nodes into more than one diagram,  as the _nodesQuery_ used the same ID for one node to store diagram information.  

The current workaround is to use a _generix box query_  instead of a _nodesQuery_ because the _generic box query_ allows you to specify the ID yourself,  so you can make a unique ID.

However,  the _generic box query_ is much more limited, and forces you to specify many details that are done more or less automatically in case of a _nodesQuery_. One specific example is e.g. that a _generic box query_ forces you to specify one node type only for the result of the query. And then you have to specify properties like the _shape_, the _editor_, etc. explicitly.  The _nodesQuery_  allows you to just return a set of randon nodes and it will automatically find the editor and shape available.

For a _nodesQuery_ that results in many different node types, I now have to filter the query by type, and use a _generic box query_ for each of these types. This blows up the code of the editor a lot.

Therefore it should be allowed to have a node visible in multiple diagrams without having to use the _generic box query_.

**Comment by slisson** [comment]
The generic box query is not a workaround, it's the only possible way. This is because of limitations in MPS.

**Comment by joswarmer** [comment]
:-(

**Comment by slisson** [comment]
I can try to make it more extensible.

**Comment by joswarmer** [comment]
Alternatively, would is be possible to make the _generic box query_ more flexible to solve some of the problems?

**Comment by joswarmer** [comment]
Just thinking aloud: would it e.g. be possible to let the generic box query refer to the diagram box editor for the parameter node type?  This could result in a lot less duplicated editor specification code, because all of the properties are defined in that editor as well.

**Comment by slisson** [comment]
I can try to invoke the cell factory for the concept directly, but I don't know how well that will work and what the side effects are.

**Comment by joswarmer** [comment]
Can you allow a reference to the nodes diagram editor from the generic box query,  and then copy that, such that it essentially becomes a short way to specify the same as we have today ?

**Comment by slisson** [comment]
This would require to reference all editors for all possible subconcepts and break extensibility.

**Comment by joswarmer** [comment]
You are right that this isn't extensible.  But,  in the current generic box query we need to specify everything explicitly for the specified node type, which cannot be overridden by possible subconcepts. Doesn't this mean that this is non-extensible either? Or am I missing some extensibility option here?

**Comment by slisson** [comment]
Yes, both options would break extensibility. That's why I'm trying to find a solution that does not require generic queries.

**Comment by slisson** [comment]
Changes related to this issue:
d1685402ade6f90048db7863eaf1c6c0dba10193
82c2513660b3e4db8d575b9439d4d28897123b04

**Comment by joswarmer** [comment]
Changing the layout only in the second diagram changes the actual model.  In 
![move-box-pre](https://cloud.githubusercontent.com/assets/818164/17658220/633cd55c-62ca-11e6-8d77-3f3d58f4d06b.PNG)
Composite A defines a model, with connections from 'str' to 'amplifier'. In Composite C I see 'amplifier' because it is inherited from 'composite A'.  When I move any element in diagram C,  or use the Fit Size of All Boxes'  option, not only diagram C changes, but the connections in diagram A are deleted from the model:
![move-box-post](https://cloud.githubusercontent.com/assets/818164/17658327/2ee5ec8e-62cb-11e6-8653-fa193b9230f4.PNG)
I am using the untested "duplicates safe" option in the definition of the diagram.
