### ISSUE TITLE
Allow to specify read-only in nodesQeury

### ISSUE THREAD

**Issue by joswarmer** [mbeddr/mbeddr.core#1472]
When a nodesQuery returns nodes coming from elsewhere in the AST is is useful to be able to define that the node (its shape and contents) is read-only in this editor.
This helps to manage diagram editors where nodes are visible in more than one edtor.

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/65)
