### ISSUE TITLE
Allow multiple lines of code in queries in diagram editor definitions

### ISSUE THREAD

**Issue by joswarmer** [mbeddr/mbeddr.core#1476]
At several places you can specify a query (e.g. for ports in a diagram.box.  These queries to be exactly one line of base language code. For debugging purposed (e.g. prinln(..) ) it would be good te be able to specify multiple lines of code.
Also, fro a consistentvy point of view this should also be done.  In MPS you can specify a query at many places but this always is a function like things where you can have multiple lines of code.

**Comment by slisson** [comment]
You can always use closures, if you need multiple lines. Most of the time only a single line is sufficient and using concept functions everywhere would blow up the code and make it harder to read.

**Comment by joswarmer** [comment]
Ok,  I can live with that,  as one line will be enough most of the time. Shall we close this issue ?
