### ISSUE TITLE
Compilation error in port definition

### ISSUE THREAD

**Issue by joswarmer** [mbeddr/mbeddr.core#1478]
In the diagram editor specification you van specify the `label` of a `port`. If the expression entered is not of type `string` the langauge built will give a compilation error:

```
The constructor Port(<<expression type>>) is undefined,
```

There shoukld be a check on the type of the `label` expression to ensure it always conforms to string.

**Comment by joswarmer** [comment]
The same holds for the values of `positionY` and `positionX`.  If the expression is not of type integer, a compilation error follows. Should also get a checking rule.

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/68)
