### ISSUE TITLE
Connection edges drawn over ports make the ports hard to select

### ISSUE THREAD

**Issue by wsafonov** [mbeddr/mbeddr.core#1507]
When a port is used to connect nodes both from the parent diagram and from the subdiagram, the connection edge could be drawn over the port and make the port hard to select at that place, because the edge would be selected instead. Either the lines should get less priority during selection, or the connection point of the edge to the port should be flexible to better support scenarios with connections from opposite sides.
![port_connection_issue](https://cloud.githubusercontent.com/assets/8157816/18714696/ec31e050-8016-11e6-86ea-a0e6f2ea005b.png)

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/70)
