### ISSUE TITLE
regression of packByteWise keyword

### ISSUE THREAD

**Issue by huibo-shi** [mbeddr/mbeddr.core#1510]
After updated to nightly 152, the struct with packByteWise keyword can't be generated correctly.
Here is my code test :

exported struct packByteWise CcomMessageType { 
  uint16 appliance_type; 
  uint16 message_type; 
  boolean is_response; 
};

Here is the code generated:

typedef #pragma pack(push, 1) struct Messaging_CcomMessageType Messaging_CcomMessageType_t#pragma pack(pop)
;
#pragma pack(push, 1)
struct Messaging_CcomMessageType {
  uint16_t appliance_type;
  uint16_t message_type;
  bool is_response;
};

**Comment by coolya** [comment]
fixed in #5a1123e6efd202bb2ba9434bae40559cc08da594
