### ISSUE TITLE
Diagram language: Interpolating points on curved edge

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#1516]
Would it be possible to add the possibility to interpolate the points on a curved edge of a diagram created with the de.itemis.mps.editor.diagram?

An interpolation may go as follows (given a very simple example): if I have two control points (0,0) and (10,0) and I interpolate the edge with a distance of 2, then I will get, for example, a list of points (0,0), (2,0), (4,0), (6,0), (8,0), (10,0).

Another way could be a way to ask the length of an edge's curve and a point on the edge between 0 and the length (or between 0 and 1, if normalized).

**Comment by slisson** [comment]
This is how you use it:

<img width="789" alt="screen shot 2016-10-07 at 10 08 49" src="https://cloud.githubusercontent.com/assets/1543361/19182915/20291cb4-8c76-11e6-830e-45f1a714f1db.png">
