### ISSUE TITLE
ConceptSwitch does not consider the variable used

### ISSUE THREAD

**Issue by ftomassetti** [mbeddr/mbeddr.core#1522]
Consider this:

```
foreach assertion in scenario.assertions { 
  conceptswitch(assertion) { 
    case AssertMessageSent : it [ ] => { 
      if (!times.contains(it.when.totalSeconds())) { 
        times.add(it.when.totalSeconds()); 
      } 
    } 
    default => { 
      // nothing to do 
    } 
  } 
}
```

I get a warning on assertion (following _foreach_). The warning tells me the variable is unused

**Comment by szabta89** [comment]
@ftomassetti Can you please verify if this issue is till present? I have tried it, but I was not able to reproduce the issue.

**Comment by alexanderpann** [comment]
Not reproducible anymore (tested again).
