### ISSUE TITLE
ConceptSwitch generate an unexpected return statement

### ISSUE THREAD

**Issue by ftomassetti** [mbeddr/mbeddr.core#1524]
In a couple of cases I have annidated ConceptSwitch. The code generated seems broken. This clause:

```
default => { 
  throw new RuntimeException("I do not know this kind of Transition: " + link.concept.getQualifiedName()); 
}
```

Is generated as:
```
if (!(branchTaken_6066125563496258435)) {
        throw new RuntimeException("I do not know this kind of Transition: " + SNodeOperations.getConcept(link).getQualifiedName());
        return branchTaken_6066125563496258435 = true;
      }
```

I would not expect the return to be present. It is a blocking issue because this code does not compile.

**Comment by atikhimirov** [comment]
Generator of ConceptSwitch merely copies what you've got there in default statement. AFAIK, it's com.mbeddr.mpsutil.blutil language that adds if() { return } code.
