### ISSUE TITLE
Problems building mbeddr.core under Linux

### ISSUE THREAD

**Issue by ftomassetti** [mbeddr/mbeddr.core#1527]
Some plugins were not copied causing all sort of errors. Tons of exceptions and the Refactoring -> Move nodes disappeared.

Wladimir helped me copying:
- com.mbeddr.mpsutil.actionsfilter
- de.itemis.mps.nativelibs.loader
- mbeddr.spawner

from the build directory to the plugins directory

**Comment by coolya** [comment]
Looks like your user has no write access to the MPS folder?

The build script we execute on linux is the same as on the Mac and there is a task that will copy them.

**Comment by coolya** [comment]
looks similar to #1284

**Comment by alexanderpann** [comment]
So much has changed since the creation of the ticket. It is therefore obsolete.
