### ISSUE TITLE
doc: Allow to define editor hints for embedded code

### ISSUE THREAD

**Issue by slisson** [mbeddr/mbeddr.core#1533]

**Comment by bkolb** [comment]
Affected concepts: ModelContentAsImageParagraph &  ModelContentAsTextParagraph

**Comment by bkolb** [comment]
The code that takes the screenshot is here: http://localhost:8080/select/tutorial/r:fd2980c8-676c-4b19-b524-18c70e02f8b7/1777614315915103325/
