### ISSUE TITLE
GrammarCells: Add check if splittable is used without property constraint

### ISSUE THREAD

**Issue by ftomassetti** [mbeddr/mbeddr.core#1569]
I am using a splittable cell with a tokenizer function containing a print statement.
I was expecting that while typing the tokenizer function would be invoked. Apparently it is not.
Am I missing how splittable work? When the tokenizer should be invoked? Is it a bug?

**Comment by slisson** [comment]
You need a property constraint. The tokenizer is invoked, when the user enters a value, that is not valid for the property.

**Comment by ftomassetti** [comment]
ah, I see! Thank you. Would it make sense to show a warning when the property constraint is not present?

**Comment by slisson** [comment]
Yes, I will add that.

**Comment by ftomassetti** [comment]
Also, now the tokenizer function is invoked and calculate different parts for my original string. However it is not clear what should happen: the cell now shows an error and contain the whole string anyway.

I have `foo` I type `$` and the tokenizer produces `[foo, $]` however the cell keeps showing `foo$`

**Comment by slisson** [comment]
If nothing happens, it means that the parser cannot find a parse tree.
