### ISSUE TITLE
Nightly archive names numbered by build

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#1576]
Please consider giving the archive names a suffix like -nightly-238-MPS-3.4.1.zip.
You already do it for the sources in the nightly build, but adding this suffix to e.g. the com.mbeddr.allInOne.zip file would be very useful for being able to distinguish downloads from different nightly builds.

**Comment by bkolb** [comment]
@DomenikP can you please have a look?

**Comment by coolya** [comment]
should be fixed. Please verify tomorrow

**Comment by DomenikP** [comment]
Is fixed. 

All artifacts now have the nightly build version + the MPS version as postfix: 
com.mbeddr.allInOne-240-MPS-3.4.1.zip
