### ISSUE TITLE
Recursive Function Calls Error

### ISSUE THREAD

**Issue by stk84** [mbeddr/mbeddr.core#1583]
When using recursive function calls, mbeddr gives the Error:

`Cycle detected between module contents in GenModuleC named <ModuleName>`

during build. The Module builds correctly and can be compiled without issues.

**Comment by fbacha** [comment]
I'm not able to reproduce this error. Is it possible to describe how it was produced ?

**Comment by stephaneberle9** [comment]
Maybe this issue has been already fixed and went away from alone since we have switched to more recent builds of mbeddr.
