### ISSUE TITLE
Code-completion menu is retained even if corresponding root node closed

### ISSUE THREAD

**Issue by Nandha1712** [mbeddr/mbeddr.core#1589]
1. Open the project calculator tutorial from MPS Samples.
2. Open the model "jetbrains.mps.calculator.sandbox.sandbox"
3. Place the cursor on the output section and press Control+Space.
4. Code Completion menu will appear. Now if we close the root node, the code completion menu should be disposed. But it stays. This menu isn't exited with 'esc' or backspace. The user is forced to select some item within the code-completion menu which will be created in the background at the initial node in which the cursor was placed.

![page1](https://cloud.githubusercontent.com/assets/10434575/20667107/a77c0358-b58d-11e6-8a52-6443427cd577.jpg)
![page2](https://cloud.githubusercontent.com/assets/10434575/20667113/aff2da0c-b58d-11e6-8117-73f0a5f4b5d6.jpg)

**Comment by alexanderpann** [comment]
This issue was reported to the wrong project at that time. The right issue tracker would have been [https://youtrack.jetbrains.com/issues/MPS](https://youtrack.jetbrains.com/issues/MPS) but this is not a known issue anymore anyway.
