### ISSUE TITLE
Message "variable may not be initialized!" has error severity bothering development with mbeddr

### ISSUE THREAD

**Issue by huibo-shi** [mbeddr/mbeddr.core#1593]
Hi,

Please have a look at the picture, there are error marks under sigInfo which indicate 'Variable may not be initialized!'. This is really annoying during the development with mbeddr because it could happen often that we declare an instance of struct and initialize it somewhere else. It would be nice if we change the error severity to warning.

![capture](https://cloud.githubusercontent.com/assets/15254833/20892817/ea7be560-bb0f-11e6-94bc-fe6863790739.PNG)

**Comment by danielratiu** [comment]
Hi,

have you marked the parameter of createCanonicalRequest as OUT ?

[image: Inline image 1]

Dan

**Comment by huibo-shi** [comment]
Hi Danielratiu,

After mark the parameter as OUT, the error is disappeared. Thanks.
