### ISSUE TITLE
No refresh of PlantUML-Visualization after first SVG per MPS-Process

### ISSUE THREAD

**Issue by mgm-sp** [mbeddr/mbeddr.core#1603]
Hi,

[Just some info that may have something to do with the issue below: http://mbeddr.com/download.html#RequiredToolsAndVersions lists the Graphviz-Version 2.30 als being supported. However, when installing mbeddr from mbeddr-win-setup-298-MPS-3.4.2.exe version 2.38 ships.]

I have the problem, that after the first PlantUML-visualization (i use github/master with MPS 3.4.2) i do not get any new Visualization, i always see the first one that i did with the current MPS-Process (also holds for using build 298 from the releases). After restart i can render another one - but just one :( .
It doesn't work for mbeddr-tutorial nor for my own IVisualizable-Implementation. 
But for each visualization-call i get one more entry in SVGViewer's history (where i can step forward and backward) but always the same SVG is being displayed.

My System: 
- Windows 7
- MPS 3.4.2 
- GraphViz 2.38
- mbeddr github/master (built from source)

If you need more info, let me know.

Regards,
Mirko

**Comment by mgm-sp** [comment]
Hi,

today i installed nightly-298-MPS-3.4.2 on a completely fresh system. The effect is the same: visualization seems not to render more than the first one (forward/backward do remember the selected categories but no re-draw is done).

Regards,
Mirko

**Comment by mgm-sp** [comment]
Hi,

i debugged a little bit and realized that the red-marked code in the screenshot below is being entered only for the first start. Is there the possibility that _stopThenRun_ checks for a condition that never turns to be true in (my?) MPS/Batik, except for the first start, for some reason?

![grafik](https://cloud.githubusercontent.com/assets/17268340/21644594/7779ea62-d28e-11e6-9e48-46adb330925f.png)

Regards,
Mirko

**Comment by coolya** [comment]
It seems to be some classloading related problem.

I can reproduce the problem.

```
java.lang.Exception: loader constraint violation in interface itable initialization: when resolving method "org.apache.batik.dom.AbstractNode.addEventListener(Ljava/lang/String;Lorg/w3c/dom/events/EventListener;Z)V" the class loader (instance of jetbrains/mps/classloading/ModuleClassLoader) of the current class, org/apache/batik/dom/svg/SVGOMSVGElement, and the class loader (instance of <bootloader>) for interface org/w3c/dom/events/EventTarget have different Class objects for the type org/w3c/dom/events/EventListener used in the signature
	at com.mbeddr.mpsutil.plantuml.pluginSolution.plugin.PlantUMLSVGDocumentLoader.run(PlantUMLSVGDocumentLoader.java:90)
```

**Comment by mgm-sp** [comment]
It now renders correctly but the linking out of the svg seems to work no more. i cross-checked the MPS-generated String via http://www.plantuml.com/plantuml. There it works and correctly links into MPS.
