### ISSUE TITLE
Collapse/Expand does not work properly for editors which use "CellModel_Diagram"

### ISSUE THREAD

**Issue by Nandha1712** [mbeddr/mbeddr.core#1604]
1. I have created a School language which contains Teachers and ClassRooms. I created diagram editor for School and its contents using "CellModel_Diagram". 
2. Changing to the diagram view using push editor hints, toggles the view to diagram view. 
3. Now if we try to collapse, the School using Ctrl+- or corresponding button, the graphical canvas stays. 
4. The view is getting more complicated, when there are multiple Schools.

The Diagram Editor definition for School,
![school_diagram_editor](https://cloud.githubusercontent.com/assets/10434575/21758205/63d986d2-d65f-11e6-9cdf-06d60588514e.jpg) 

The contents in expanded state,
![3 schools normal state](https://cloud.githubusercontent.com/assets/10434575/21758207/6a0a649a-d65f-11e6-82be-c6ba5cfd5024.jpg) 

When all the Schools are collapsed,
![3 schools collapsed](https://cloud.githubusercontent.com/assets/10434575/21758209/6defaef8-d65f-11e6-99bd-2feacb1cb31f.jpg)

**Comment by slisson** [comment]
It's an MPS bug: https://youtrack.jetbrains.com/issue/MPS-25164

**Comment by Nandha1712** [comment]
This is fixed in MPS 2017.1.2
