### ISSUE TITLE
Dropping from diagram palette does not work properly

### ISSUE THREAD

**Issue by Nandha1712** [mbeddr/mbeddr.core#1605]
1. I have created a language which uses, mbeddr's CellModel_Diagram.
2. When i tried to drop a component from diagram palette, the dropping action is not happening properly.
3. The canDrop() section gets executed. But drop() section does not get executed though canDrop() returns true explicitly.
![drag and drop](https://cloud.githubusercontent.com/assets/10434575/21804501/54045f56-d755-11e6-8595-3e88ac918eb1.png)

**Comment by slisson** [comment]
This feature only works with palette entries of type AbstractDragPaletteEntry. This is also known to not work on windows.

**Comment by Nandha1712** [comment]
Thank you. But may i know why drop() does not work on windows? Is it due to the library jgraphx? Since it is built using java, it should work on all the Operating Systems right?

**Comment by slisson** [comment]
The only thing I know is that on windows the drop event is not created. I already tried to find the reason but no luck so far.

**Comment by Nandha1712** [comment]
Okay. Thank you

**Comment by Nandha1712** [comment]
@slisson Is there any progress regarding this issue?

**Comment by slisson** [comment]
No, at the moment we don't need this feature and don't have time to work on this.

**Comment by Nandha1712** [comment]
Okay .

**Comment by slisson** [comment]
Fixed in f32a8896762c8ca383b2666258a4b1220c335a3f
