### ISSUE TITLE
Generalize path variable support in build confiugrations and add support for specifying simple variables and environment variables

### ISSUE THREAD

**Issue by fbacha** [mbeddr/mbeddr.core#1620]
- Prefix path variables as the following: ${path_var:smartmeter.code}
- Prefix environment  variables as the following: ${env_var:USERPROFILE}
- Propose custom variables: ${HOME}
All these variables should be evaluated and substitued by mbeddr

**Comment by coolya** [comment]
Path variables know to MPS are already supported using `${smartmeter.code.home}`. At least in all the path related text fields of the build config.

**Comment by fbacha** [comment]
We would like to generalize using variables to define paths in build config. In addition to MPS path variables, we will give the possibility also to use environment variables when defining paths. Of course,  those variables values will be dynamically interpreted and integrated in the generated makefile.

**Comment by alexanderpann** [comment]
Closing because it seems to be fixed in https://github.com/mbeddr/mbeddr.core/pull/1647.
