### ISSUE TITLE
Automatic substitution/scoping seems not to work anymore since 3.4.3

### ISSUE THREAD

**Issue by hnehls** [mbeddr/mbeddr.core#1624]
I use tables to define model data. These tables use (smart-)references to concept instances in their table column header.
With 3.4.2 the CompletionMenu was filled correctly; see ![3 4 2](https://cloud.githubusercontent.com/assets/22174358/22730644/1f0ec576-ede8-11e6-92af-6803e99dfc57.png)

Since upgrade to 3.4.3 the menu is not filled anymore; see ![3 4 3](https://cloud.githubusercontent.com/assets/22174358/22730645/1f118c7a-ede8-11e6-976a-c8fb777c66d0.png)

I've created a small sample project that works well with 3.4.2 but shows the explained behavior with 3.4.3; see [sampleProj.zip](https://github.com/mbeddr/mbeddr.core/files/760148/sampleProj.zip)

There is also an issue at Jetbrains: https://youtrack.jetbrains.com/issue/MPS-25165

**Comment by slisson** [comment]
Is fixed since Feb 3rd.
