### ISSUE TITLE
GrammarCells: optional side-transformations from parent after optional part in child

### ISSUE THREAD

**Issue by wsafonov** [mbeddr/mbeddr.core#1629]
If there is an optional part in the parent that should follow the current node, trying to add it by a side-transformation will not work after an optional part in the current node. 

Currently the workaround is to explicitly and manually add side-transformations from the parent for the current node. However, this leads to a side effect that unwanted side-transformations might be added (only side-transformations for immediately following optional parts in the parent should be added).

See an example in IETS3 for NumberType that is used in Typedef
![optionalparts](https://cloud.githubusercontent.com/assets/8157816/22936294/5c1fc2ac-f2d5-11e6-89ad-83cf325be7e0.png)

**Comment by alexanderpann** [comment]
I am closing because this issue doesn't exist anymore.
