### ISSUE TITLE
Missing plugins for MPS 3.4.x?

### ISSUE THREAD

**Issue by manuelesimi** [mbeddr/mbeddr.core#1645]
Hello, 

We have MPS plugins that depend on your plugins (Richtext, for instance). At this time, our users are unable to install our software because mbeddr plugins are not available. In fact, using your plugins manager, our dependencies are not resolved. Even downgrading to MPS 3.4.1 doesn't help. 
For sure, they were available when we migrated to MPS 3.4.x. Now they seem disappeared.

Can you please provide advice?

thanks,
manuele

**Comment by slisson** [comment]
They are available now for MPS 3.4.3
