### ISSUE TITLE
Cannot use a predefined variable in For loop initialization

### ISSUE THREAD

**Issue by aswinsugumaran** [mbeddr/mbeddr.core#1646]
Hello, 
       I have a variable declared outside the for loop.When i try to reuse the same variable again in initialization part of the for loop its not visible. I have tried this with some other loops statements which works fine. Only for the For loop it doesn't seem to work only at the initialization part.Any suggestion would be of great help.

![forloop](https://cloud.githubusercontent.com/assets/25502999/23700108/da50f260-0417-11e7-90c2-230827b54dd3.png)

**Comment by aswinsugumaran** [comment]
a

**Comment by aswinsugumaran** [comment]
@coolya  from what i inferred we have this constraint named ForVarRef_Constraints which returns false cause of iterator is null at time of for loop initialization. I set the constraint to be true manually which works now. Is this the proper solution for this or any other alternate solution is there?

**Comment by coolya** [comment]
I will have a look at this tomorrow. From you error description I don't really understand what the issue is. I guess `ix` is not in scope, right?

Can give a text example what you want code you would like to write?

**Comment by aswinsugumaran** [comment]
@coolya  the ix is in the scope. 
Steps to reproduce 
1. Create a local variable
2. Try to use the local variable in the simple for loop
3. The local variable will not be available in the code completion menu of for loop initialization part.

![forloop1](https://cloud.githubusercontent.com/assets/25502999/23750878/eeb51226-04f4-11e7-84ba-fcc6e35a26d4.png)

**Comment by coolya** [comment]
What you do at that location is defining the iterator. There is no way to use `ix` at that location. 

Once again, please give me a **text**  example of the code you would like to be able to enter.

**Comment by aswinsugumaran** [comment]
Example
int a;

for( <the variable 'a' should be listed here when i use the code completion menu > ;    ; )

**Comment by coolya** [comment]
I don't think this makes much sense. According to the C99 spec 6.8.5.3 a for statements is defined like this:

```for ( clause-1 ; expression-2 ; expression-3 ) statement```

Where clause-1 can either be a declaration, which would make it a variable with a scope within the for loop, or a void expression.

The void expression case is not supported by mbeddr, you are only allowed to declare a variable at that location. 

What should work is something like 
```

int16 a;

for (int16 i = a; a++ ;) {
}

```

**Comment by DineshLMS** [comment]
@coolya I don't think it was implemented keeping C99 standard in mind. It was working previously. I couldn't understand how it was working in previous releases (25/11/2016) and not working all of sudden after migration to MPS 3.4.3 and gradle build. any idea ?

**Comment by slisson** [comment]
It works if I delete the constraint ForVarRef.canBeChild.

**Comment by DineshLMS** [comment]
@slisson That is what @aswinsugumaran is also proposing now and asking @coolya to give suggestions or comments

**Comment by aswinsugumaran** [comment]
https://github.com/mbeddr/mbeddr.core/pull/1661
