### ISSUE TITLE
Wrong bi-dimensional array indices order

### ISSUE THREAD

**Issue by AntosDR** [mbeddr/mbeddr.core#1648]
Hello!
I wrote a little application which uses a bi-dimensional array of booleans and I experienced a lot of segmentation faults... After debugging the generated C code I found that the declaration of my bi-dimensional array has indices inverted.
The image below explains better the issue:

![mbeddr-bug](https://cloud.githubusercontent.com/assets/26299632/23747969/f4b48446-04c1-11e7-9f8f-e4d5385988e6.PNG)

As you can see, the declared array is "topic x subscriber", the generated C array is "subscriber x topic". This is not a severe problem if accessing the indices uses the same inverted order, but the generated C array accessing code uses the right order! This will result in a segfault directly or in a following memory access.

I'm using MPS 3.4.3 with the nightly build 501 on linux 64bit system.

**Comment by alexanderpann** [comment]
I am closing because this is explained in the [user guide](http://mbeddr.com/userguide/UserGuideExport.html#sid3592268205546300997):

> One of the fundamental differences compared to C in mbeddr is the way how arrays are declared. In C, array declarations are hard to read when they incorporate pointers and/or the const and volatile modifier. In mbeddr, arrays are declared and read from right to left. This might be different compared to other languages that you are used to, but in order to make reading types consistent across mbeddr, we had to introduce this. 

Example in C:
```
int16[3][2] integers;
```
Example in mbeddr: 
```
int16[2][3] array = {
  {1, 2},            
  {3, 4},            
  {5, 6}             
};
```
