### ISSUE TITLE
math.parentheses does not consider Darcula style

### ISSUE THREAD

**Issue by hnehls** [mbeddr/mbeddr.core#1651]
When using Darcula-Theme, the parentheses, rendered by math.parentheses, stay black but should be white. Also I could not find any corresponding style attribute (just 'bracket-color' and 'background-color' but both do not match, I guess and anyway, they have no effect).
Same issue with DivisionEditor.

In math.sum it works fine.

![darcula](https://cloud.githubusercontent.com/assets/22174358/23801608/0826b6da-05b1-11e7-8aaf-4966659baf52.png)

**Comment by hnehls** [comment]
> In math.sum it works fine

Well, for the brackets, but not for the sum symbol ;)

**Comment by slisson** [comment]
There should be "symbol-color" style. Maybe that one works. But I will fix the default color.
