### ISSUE TITLE
Actions for CellModel_Collapsible

### ISSUE THREAD

**Issue by josefmueller** [mbeddr/mbeddr.core#1654]
It would be really handy if MPS folding actions (bellow) could be used also for CellModel_Collapsible. Would it be possible?

![image](https://cloud.githubusercontent.com/assets/15520928/23856918/8b21e4a0-07fb-11e7-89da-8e18edc4761e.png)

Are there any actions like these for CellModel_Collapsible?

**Comment by alexanderpann** [comment]
Duplicate of https://github.com/JetBrains/MPS-extensions/issues/573.
