### ISSUE TITLE
Generation of unsupported format tags in log output

### ISSUE THREAD

**Issue by muehlbrandt** [mbeddr/mbeddr.core#1656]
Some of the generated format tags for expressions used within log output are not supported by every target platform. This happens especially with format tags for integers (e.g. %hhu).

**Comment by coolya** [comment]
I think the short term solution is to get rid of the unsupported format specifiers in the current implementation of the types.

The long term solution is IMHO to refactor the whole `getFormatString` methods to dispatch into the typesizeconfig or platform which hold the compiler. I'm not sure where is the better place. @stephaneberle9 What's your opinion on this?

**Comment by stephaneberle9** [comment]
Dup of #2083
