### ISSUE TITLE
Bug: No error raised when a constant global variable value is modified

### ISSUE THREAD

**Issue by fbacha** [mbeddr/mbeddr.core#1658]
Actually, no error is raised when we try to modify the value of a constant global variable. However, it should be the case.
**PS**: the same example execution under CDT produces an: "assignment of read-only location" error.
![noerrorraised](https://cloud.githubusercontent.com/assets/4094172/24244239/51af7ee2-0fbe-11e7-98df-ff750a15adda.png)

**Comment by alexanderpann** [comment]
This issue was also fixed a long time ago.
