### ISSUE TITLE
Debugger doesn't show values for struct pointers

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#1662]
For a model that reproduces this, please refer to: https://github.com/DSLFoundry/mps-examples/tree/master/issue-reports/mbeddr-debugger-struct-values-not-shown
When I make a C model with a function that has a pointer to a struct as a parameter, then the debugger doesn't show the value of the struct's fields:
![image](https://cloud.githubusercontent.com/assets/6429350/24302295/6f92136c-10b2-11e7-98d4-2000f2656c8e.png)
now ap_Entry->val = MyStructEntry
I would expect that ap_Entry->val = 0 or possibly some other uninitialized double value

**Comment by alexanderpann** [comment]
The debugger was removed in https://github.com/mbeddr/mbeddr.core/pull/2509. The ticket is now obsolete.
