### ISSUE TITLE
Filling in function arguments is quite un-explorable

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#1663]
Currently, if I have to enter a C function, I have to go back to the function definition in order to know which arguments I can fill in. Since this is a case that is often used, maybe some mechanism can be added to easily add some example parameters to a function call? Maybe an intention?

**Comment by markusvoelter** [comment]
Tried pressing Ctrl-P?

**Comment by eugenschindler** [comment]
Yeah, that helps :) Thanks for the hint, Markus!
Would it be possible to do it like you see in "normal" IDEs, that you see which parameter to type, as you type them?

**Comment by slisson** [comment]
It's implemented in MPS and has to be changed there.

**Comment by eugenschindler** [comment]
Thanks for the information, @slisson. Do you know if there is already a YouTrack issue for it that I can +1 or did no-one make one yet?

**Comment by slisson** [comment]
I don't know of any existing issue.

**Comment by eugenschindler** [comment]
I made an issue here: https://youtrack.jetbrains.com/issue/MPS-25853
