### ISSUE TITLE
Keywords "break" and "continue" in foreach loops

### ISSUE THREAD

**Issue by andreasgrosche** [mbeddr/mbeddr.core#1678]
It would be useful if break and continue would be supported in foreach loops.

The mbeddr version is 501.

In for loops, break and continue are supported:
```
for (uint8 i = 0;i < 10; i++ ) { 
  break; 
  continue; 
} for 
```

In foreach loops, break and continue are not supported:
```
foreach (channels sized 10 as it) { 
  // break is not supported in foreach loop 
   
  // continue is not supported in foreach loop 

}
```

**Comment by alexanderpann** [comment]
It seems to be supported in newer versions.
