### ISSUE TITLE
Two unnamed context actions tabs showing

### ISSUE THREAD

**Issue by ftomassetti** [mbeddr/mbeddr.core#1680]
![screen shot 2017-04-18 at 10 17 25](https://cloud.githubusercontent.com/assets/439078/25120953/438672d2-2420-11e7-9fd9-1fd3a78a2f04.png)

Nothing is showing when I select the first tab, while on the second I can see all the context actions I have added.

Not sure why this is happening. Any idea?

**Comment by aswinsugumaran** [comment]
I faced this problem too. As of temporarily i manually rebuild the particular plugin responsible for the Context-actions and the tabs are gone!It works as expected.

**Comment by ftomassetti** [comment]
Hi @aswinsugumaran we have rebuilt it many times but we have still the double tabs unfortunately

**Comment by ftomassetti** [comment]
I suspect there are two instances of `ToolComponent` but I do not why or how to prevent this from happening. Both the instances have the search widget, but just one list the context actions. Could be possible that somehow there are two versions of the mpsutil plugin?

**Comment by ftomassetti** [comment]
I understand this is a very minor issue and there are hundreds of more pressing issues w.r.t. this one but I was wondering if there was any progress on this one

**Comment by sergej-koscejev** [comment]
The cause is that there's a Context Actions tool in MPS now, more or less copied from the mbeddr tool (but using the transformation menu language to define actions). Since they both have the same name, they show up in the same place but as two tabs. The easiest fix would be to rename the mbeddr tool to "Context Actions (mbeddr)".

**Comment by markusvoelter** [comment]
Are you sure that this is the issue? I am pretty sure we had the double-tab issue before MPS had context actions.

**Comment by aswinsugumaran** [comment]
Now i have two context-actions are on my window after this fix. Any idea to replace the context-actions from MPS ?

**Comment by sergej-koscejev** [comment]
@aswinsugumaran disable "MPS Context Actions Tool" plugin

**Comment by aswinsugumaran** [comment]
@sergej-koscejev  works thanks :)

**Comment by aswinsugumaran** [comment]
@sergej-koscejev  is there a chance we can enable this setting defaultly off from Mbeddr context actions ?

**Comment by sergej-koscejev** [comment]
I don't fully understand what you mean, please elaborate.

**Comment by aswinsugumaran** [comment]
Instead of going to settings and disabling the MPS context actions, can we do this inside Mbeddr context actions so that it automatically removes the MPS context actions?

**Comment by sergej-koscejev** [comment]
I don't know if it's possible but I wouldn't do it. You can remove the MPS context actions plugin when you package your own MPS-based RCP.

**Comment by vsnarendran** [comment]
Yes Aswin. We can remove the plugin MPS201712\plugins\context-tool that will remove the tab from mps.
