### ISSUE TITLE
MacroFolderPicker: empty path is not supported

### ISSUE THREAD

**Issue by ChristianBuckl** [mbeddr/mbeddr.core#1685]
When using the MacroFolderPicker you might want to point to the folder that is defined by the macro.
If the path is left empty for an MacroFolderPicker, getCanonicalPath will return null. However, no error is displayed to the user.
You can achieve the expected behavior by using "." as path.

Preferred solution: return the folder defined by the path variable, if the path is left empty.
Acceptable solution: display an error for MacroFolderPicker, if the path is empty.

**Comment by bkolb** [comment]
For me ```${xxxxx}/<no path>``` works as expected. I am getting the value of `xxxxx` from getCanonicalPath
