### ISSUE TITLE
GrammarCells wrap do not consider constraints

### ISSUE THREAD

**Issue by ftomassetti** [mbeddr/mbeddr.core#1687]
I have a case in which I have an editor containing a wrap grammar cell. The concept of the editor is not allowed in a certain context but the substitution happens anyway, resulting in an invalid model.

**Comment by slisson** [comment]
What type of constraint is it? A wrapper substitute actions can only check the "canBeChild" constraint of the parent.

**Comment by ftomassetti** [comment]
It is a canBeChild that applies to the new node being created to replace the existing one

**Comment by slisson** [comment]
It's not possible to check the constraint before the node is created. As an alternative you can try to specify a condition in the inspector of the wrapper cell.

**Comment by ftomassetti** [comment]
That does not seem to work. Consider this:

![screen shot 2017-05-01 at 10 47 54](https://cloud.githubusercontent.com/assets/439078/25575952/bf6c7a64-2e5b-11e7-91a0-a3f116f7d629.png)

None of this is invoked.

In this case I have a number, when I type "in" two things happen: first this transformation is executed, wrapping the number in this concept, then a second transformation happens so that the new node (result of the first transformation) is inserted in a larger expression.

**Comment by slisson** [comment]
I tried to reproduce it here: https://github.com/slisson/mbeddr-1687 (I used MPS 2017.1), but without success. In my case the condition is evaluated. Can you check the example a try to find the difference?

**Comment by ftomassetti** [comment]
We are on MPS3.4.3 (we cannot migrate for the time being). I think it is relevant that this issue appear only when we have two transformations concatenate. The single wrapping action is never being executed alone, only when we type "in", triggering another transformation.

**Comment by ftomassetti** [comment]
I have looked at your example and it seems to use only a wrapping element.

In my case I have a concept named `EqualToContextualExpression`. Its editor wraps an `Expression`.

When I edit code in a context in which `EqualToContextualExpression` can be used, it is replaced corrently. The print statements I have added are executed, so the conditions are evaluated.

However, in a context in which `EqualToContextualExpression` cannot be used, when I type `in` an `InRangeExpression` is added. It has this editor:

![screen shot 2017-05-03 at 14 14 36](https://cloud.githubusercontent.com/assets/439078/25660062/ea2ecf12-300a-11e7-9910-736889931c95.png)

Now, when typing `in` I end up with my an `InRangeExpression` wrapped into a `EqualToContextualExpression`. In this case the conditions are not evaluated (no print statements). I think I have seen the `EqualToContextualExpression` used to wrap only the `value` element of the whole `InRangeExpression` other times but this is the case I report in the screenshot below:

![screen shot 2017-05-03 at 14 19 06](https://cloud.githubusercontent.com/assets/439078/25660205/82a0b4fe-300b-11e7-87e3-9c27c722e3e9.png)

I hope it helps figuring out why conditions are not evaluated

**Comment by slisson** [comment]
A minimal example project would be even more useful. Then I don't have to (mis-)understand your description.

**Comment by ftomassetti** [comment]
I have created one in https://github.com/ftomassetti/mbeddr1687b 

Also in this case I added some print and verified that they are not executed.

In the example solution I create `ExpressionsList`, type a number (e.g. 1) and type `in`. The whole expression is wrapped into an EqualToContextualExpression but the condition are not verified.

**Comment by slisson** [comment]
This seems to be a bug in parser of the grammarCells. You can work around it by adding some constants to the grammar of EqualToContextualExpression. Then the concept is not added when it wasn't there before.

<img width="646" alt="screen shot 2017-05-03 at 15 15 19" src="https://cloud.githubusercontent.com/assets/1543361/25662134/ac290f8a-3013-11e7-8dfc-ca930def2e5a.png">

**Comment by ftomassetti** [comment]
The workaround you suggested worked on our particular project. Thanks!
