### ISSUE TITLE
Followup on upstream bugs regarding crossmodel generation

### ISSUE THREAD

**Issue by coolya** [mbeddr/mbeddr.core#1696]
- [ ] https://youtrack.jetbrains.com/issue/MPS-25933
- [ ] https://youtrack.jetbrains.com/issue/MPS-25932

**Comment by alexanderpann** [comment]
Closing because [MPS-25932](https://youtrack.jetbrains.com/issue/MPS-25932) is fixed, [MPS-25933](https://youtrack.jetbrains.com/issue/MPS-25933) is also most likely fixed.
