### ISSUE TITLE
Auto-Layout not works properly in State machine graphical

### ISSUE THREAD

**Issue by aswinsugumaran** [mbeddr/mbeddr.core#1708]
![issue_screen](https://user-images.githubusercontent.com/25502999/27371930-4c5f9d42-5680-11e7-8a4b-938abbb560cc.PNG)
Hi,

I have attached a sample model of state machine represented graphically,from the model in the composite state **State1** when i do auto layout, nothing happens and also there is transition appearing behind **state2** composite state. When there is nested boxes, auto layout doesn't work either. Any suggestion to fix it would be of great help.

**Comment by DomenikP** [comment]
@slisson 
Do you have an idea?

**Comment by slisson** [comment]
Auto layout of edge across (sub-)diagram is not supported at the moment. Each (sub-)diagram is layouted individually.

**Comment by aswinsugumaran** [comment]
@slisson  will there any update on this in upcoming days?

**Comment by slisson** [comment]
The are no plans to implement this feature.
