### ISSUE TITLE
Facet for coping generated documentation

### ISSUE THREAD

**Issue by coolya** [mbeddr/mbeddr.core#1722]
Create a facet that copy every documentation related file into doc_gen folder next to the source_gen folder

**Comment by joao-silveira** [comment]
More or less related, there was already a facet for copying in the generated images:

http://127.0.0.1:63320/node?ref=r%3Aa38f0e6e-eb07-4712-927b-30c9e021556c%28com.mbeddr.doc.gen_xhtml.plugin%29%2F205505736075693674

I guess it got broken somewhere in time.

**Comment by coolya** [comment]
Interesting, didn't know about that one. 

What do you think makes more sense, trying to repair it or rewrite it with the experience of the past weeks?

**Comment by alexanderpann** [comment]
This was implemented in #2240.
