### ISSUE TITLE
Empty plugin "com.mbeddr.mpsutil.ecore" is packaged in mpsutil

### ISSUE THREAD

**Issue by joao-silveira** [mbeddr/mbeddr.core#1733]
Today I was doing some changes in `com.mbeddr.platform` build script and found something weird.

There is a plugin called `com.mbeddr.mpsutil.ecore` that is being packaged with the platform but it seems to be empty as all the languages/solutions that should be contained in it are commented out in the build script.

Can you please take a look?

**Comment by krishnanm86** [comment]
Sure. Will do.

**Comment by arimer** [comment]
@krishnanm86  can you please have a look at it? maybe you can sync with @bkolb to find out what the problem was/is and fix it?
