### ISSUE TITLE
Find (CMD+F) loses focus when diagram was active

### ISSUE THREAD

**Issue by slisson** [mbeddr/mbeddr.core#1735]
After typing the first character in the find textbox it loses the focus.

**Comment by slisson** [comment]
The find bar sets the selection to the first matching cell. In case of diagram cells, they activate the editing mode and steal the focus.

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/59)
