### ISSUE TITLE
Mbeddr Version

### ISSUE THREAD

**Issue by DorelComan** [mbeddr/mbeddr.core#1737]
The version of mbeddr is alway 1.0.0 like in the screenshot

![image](https://user-images.githubusercontent.com/10052001/29268468-2b542806-80ed-11e7-873c-cac5bad2f6ee.png)

Should we make the versioning dynamic according to the version of the build? (not the one in the photo which is always the same)

**Comment by danielratiu** [comment]
the version now is taken from the branding - closing this now
