### ISSUE TITLE
wrapper cell does not work with editor hints

### ISSUE THREAD

**Issue by arimer** [mbeddr/mbeddr.core#1739]
The usage of grammar.wrap in combination with an editor hint, does not work properly: 

![grafik](https://user-images.githubusercontent.com/16648247/29273344-3b5c7160-8104-11e7-9067-8aaf0d874569.png)

No substitution menu for wrapping the node is generated.

**Comment by arimer** [comment]
Workaround: implementing the substitute menu for wrapping the childnode yourself

**Comment by alexanderpann** [comment]
Not reproducible anymore. It works with editor hints now.
