### ISSUE TITLE
diagram language does not reexport diagram.runtime solution

### ISSUE THREAD

**Issue by DomenikP** [mbeddr/mbeddr.core#1743]
The de.itemis.mps.editor.diagram language does not reexport its runtime solution (de.itemis.mps.editor.diagram.runtime). Other MPS projects using the diagram language will face compilation problems in the command-line build, since the Java classes from the diagram.runtime solution are not added to the classpath.

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/60)
