### ISSUE TITLE
make for mdcc_documentation_examples fails without git clean

### ISSUE THREAD

**Issue by coolya** [mbeddr/mbeddr.core#1747]
If mbeddr is build without a git clean the build fails with the error:

` [generate] make failed with exit code 2 for com.mbeddr.analyses.spin.documentation/com.mbeddr.analyses.spin.documentation.mdcc_documentation_examples`

If a git clean is done, the build works fine. It seems there is some clean rule missing in our clean task.

**Comment by danielratiu** [comment]
closed by commit   0577dec9ac91213ce5ba777a580fdbd71636ec36
