### ISSUE TITLE
Error while commenting out a Requirement

### ISSUE THREAD

**Issue by josefmueller** [mbeddr/mbeddr.core#1758]
If the intention "Comment Out" is used on a Requirement, error is thrown and Reflected editor is shown:

![image](https://user-images.githubusercontent.com/15520928/30322245-156032be-97b9-11e7-959c-cf6453ba666d.png)

![image](https://user-images.githubusercontent.com/15520928/30322302-4a42a6ba-97b9-11e7-89d8-3423c1b96713.png)

Error:

![image](https://user-images.githubusercontent.com/15520928/30322307-4fbffb4c-97b9-11e7-9b58-64e363d7e291.png)

**Comment by alexanderpann** [comment]
Fixed on [**maintenance/mps20222**](https://github.com/mbeddr/mbeddr.core/tree/maintenance/mps20222) **in** 4bb452e.
