### ISSUE TITLE
typedef of an enum comes before an enum in the generated code

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#1759]
When declaring an enum like this in mbeddr:

```
exported enum myEnum {
  item1;
  item2;
}
```

The enum gets generated to the following code:
```
typedef enum MyModule_myEnum MyModule_myEnum_t;
enum MyModule_myEnum{
  item1;
  item2;
};
```

This gives a compilation error when compiling with -Wall
Can you make it so that the enum gets generated before the typedef in the generated text?
So then the generated code will look like this:
```
enum MyModule_myEnum{
  item1;
  item2;
};
typedef enum MyModule_myEnum MyModule_myEnum_t;
```

**Comment by krishnanm86** [comment]
Fixed. The enums are now generated before the typedef
