### ISSUE TITLE
mbeddr and AUTOSAR

### ISSUE THREAD

**Issue by josefmueller** [mbeddr/mbeddr.core#1779]
Hi all,

Is it possible to use mbeddr with AUTOSAR specifications as it stated here (http://www.bmw-carit.de/downloads/presentations/SimplifyingComplexEmbeddedDevelopmentProcessesWithMbeddr.pdf)?

I was not able able to find languages which support AUTOSAR specific language extensions, as well as the model transformation to Artop. Where do I find those?

Thank you in advance.

**Comment by danielratiu** [comment]
Hi Josef,

During the research project when BMW-Car IT was involved, we just
prototyped support for AUTOSAR. That prototype was not maintained /
developed any longer.

AUTOSAR support was re-implemented as part of Embedded Software Designer
(ESD) - the tool built by Siemens.

Dan
