### ISSUE TITLE
Errors in DocumentConfig

### ISSUE THREAD

**Issue by josefmueller** [mbeddr/mbeddr.core#1786]
Hi all,

If create RequirementsModule, it automatically creates DocumentConfig but there is following error shown:

![image](https://user-images.githubusercontent.com/15520928/31990205-b623a852-b974-11e7-9418-c0b7042bdabf.png)

There is no way to add defaultImagePath.

If I create a new DocumentConfig manually following error is shown:

![image](https://user-images.githubusercontent.com/15520928/31990276-e691bc04-b974-11e7-8f7c-b4e2e8531684.png)

I am not sure about which folder is this error talking about.

**Comment by coolya** [comment]
This user shouldn't be able to pic this location anyway because the generator will override it. I think we should remove this child and find a different solution.

**Comment by alexanderpann** [comment]
The original issue is now fixed in maintenance/mps20222 in https://github.com/mbeddr/mbeddr.core/commit/4313c96d94483446a63046e89408daab7eaade8e
