### ISSUE TITLE
Parameters and variable names starting with fo cannot be typed in

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#1788]
How to reproduce:
Try to type in a normal mbeddr module things like this:
 double fork; // the fo will be a variable and the rk part will be unbound
 void f(double format) // again the fo will be a parameter and the rmat part will be unbound

Expected would be that one can use names for variables and parameters that start with fo (like in the examples above).

**Comment by danielratiu** [comment]
>>void f(double format) // again the fo will be a parameter and the rmat part will be unbound
this works here

the case with global variable is a deeper issue ... assigned it to the editors guru

**Comment by aswinsugumaran** [comment]
Similar issue inside Struct unable to create a member name *constantVar*
