### ISSUE TITLE
Generator fails when using a query for border-size

### ISSUE THREAD

**Issue by slisson** [mbeddr/mbeddr.core#1799]

**Comment by alexanderpann** [comment]
If this is about [BorderSizeStyle](http://127.0.0.1:63320/node?ref=r%3Abb8c05bc-4758-44fe-b1ab-f9faa5a73d31%28de.itemis.mps.editor.celllayout.structure%29%2F2728748097294695721&project=mps-extensions), then the ticket is obsolete.
