### ISSUE TITLE
Transformation of TakeStatement in com.mbeddr.ext.concurrency

### ISSUE THREAD

**Issue by wuryel** [mbeddr/mbeddr.core#1800]
During Transformation of `TakeStatement ` in com.mbeddr.ext.concurrency the local variable `___val` is initialized with 0, which may lead to an "invalid initializer" error in case the queues data type is no nummeric.
see [here](http://127.0.0.1:63320/node?ref=r%3A9ee94508-9417-4d96-92d1-0929f29534d4%28com.mbeddr.ext.concurrency.pthreads.generator.template.main%40generator%29%2F1787645152765316538)

127.0.0.1:63320/node?ref=r%3A9ee94508-9417-4d96-92d1-0929f29534d4%28com.mbeddr.ext.concurrency.pthreads.generator.template.main%40generator%29%2F1787645152765316538

**Comment by krishnanm86** [comment]
@wuryel I have removed the initialization from the generator and the changes are available in the master of mbeddr. The value must be assigned to only from the data in the queue which happens later in the generated code anyway, so the initialization to 0 does not impact anything.
