### ISSUE TITLE
Add Documentation Refactoring does not set correct focus

### ISSUE THREAD

**Issue by arimer** [mbeddr/mbeddr.core#1802]
When using this refactoring shortcut: **Ctrl + A**
http://127.0.0.1:63320/node?ref=r%3A58da145a-b160-4754-a2e7-7dfa1451f846%28com.mbeddr.core.base.refactorings%29%2F3857533489766801296

The comment is created but the focus is not set to the right editor cell.

**Comment by arimer** [comment]
Proposed solution:
-Remove the refactoring + the refactoring action
-Implement a new action with the same keybinding
-Inside the action we have access to the editor context and set the right focus there

**Comment by alexanderpann** [comment]
Closing because it seems to be fixed in https://github.com/mbeddr/mbeddr.core/pull/1803.
