### ISSUE TITLE
Breadcrumb does not seem to work in MPS

### ISSUE THREAD

**Issue by davidnemeti** [mbeddr/mbeddr.core#1813]
Breadcrumb does not seem to work, at least I cannot get it to work.

Two of my concepts implements `IBreadcrumb`, and the root of the editor include breadcrumb editor at the top, however, I cannot see any breadcrumb widget anywhere (a have rebuilt the project, and even restarted MPS):

![breadcrumb](https://user-images.githubusercontent.com/2950024/33063392-9ca4c2c4-cea2-11e7-96a4-83b7467ffcba.jpg)

I am using the MPS 2017.2.2 + mbeddr 2017.2.0 (Plugin Distribution) combo.

**Comment by alexanderpann** [comment]
Closing because the deprecated breadcrumb language was removed in https://github.com/mbeddr/mbeddr.core/pull/2195.
