### ISSUE TITLE
The generation for Grammar Cells' "optional" fails when using with references

### ISSUE THREAD

**Issue by davidnemeti** [mbeddr/mbeddr.core#1815]
The generation for Grammar Cells' "optional" fails when using with references.

![grammarcellsoptional](https://user-images.githubusercontent.com/2950024/33078252-62087aae-ced2-11e7-919b-d899eaa64093.png)

I am using the MPS 2017.2.2 + mbeddr 2017.2.0 (Plugin Distribution) combo.

**Comment by alexanderpann** [comment]
I am closing this ticket as references are now supported.
