### ISSUE TITLE
clean up mess in grade scripts

### ISSUE THREAD

**Issue by coolya** [mbeddr/mbeddr.core#1837]
The code for installing the plugins into the current mps instance is quite scattered around in the build scripts. We should rework it so it because easier to debug and understand. 

Most notably the check is the property has been set is somewhere totally different that the rest of it:

https://github.com/mbeddr/mbeddr.core/blob/master/build/com.mbeddr/languages/build.gradle#L70

**Comment by szabta89** [comment]
Also, I want to point out that the script does not say anything about the usage of the MPS_PATHS_SELECTOR part. Based on debugging the script, it is clear that one should just pass in the name of the path selector and not a fully qualified path, but it would be nice if we could make this somehow explicit. Even a short textual info would do a lot.
