### ISSUE TITLE
Parallel build in mbeddr not working

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#1838]
Just migrated to MPS 2017.3-based mbeddr. Default number of cores in build configuration is set to 7. This makes the build hang without ever returning.
If I set the number of cores to 1 (leading to a make -j1 instead of make -j7), then there is no problem. Tried to check if this behaves different on the command line, but there a make -j7 also gets stuck. Must be something in the makefile, but I don't know what (yet).

**Comment by krishnanm86** [comment]
Hi Eugen,
        Could you please attach a zip of the generated sources to reproduce the bug and find out the source of the issue.

**Comment by krishnanm86** [comment]
Closing this after fixing it offline. The issue is related to gnu make 3.81 and is a known issue with parallel makes using this make.

**Comment by coolya** [comment]
could we do a version detection in the make facet and show an error to the user if we detect that faulty make version?

**Comment by krishnanm86** [comment]
This should be possible. Created a new issue #1865
