### ISSUE TITLE
Display of debug variables broken

### ISSUE THREAD

**Issue by stephaneberle9** [mbeddr/mbeddr.core#1842]
In the recent mbeddr builds, the debugger does no longer display any variables:

![image](https://user-images.githubusercontent.com/1942528/34211458-70d4c758-e599-11e7-8038-26b93c787e28.png)

**Comment by stephaneberle9** [comment]
Could be related to this issue: https://youtrack.jetbrains.com/issue/MPS-27186

**Comment by alexanderpann** [comment]
The debugger was removed in https://github.com/mbeddr/mbeddr.core/pull/2509. The ticket is now obsolete.
