### ISSUE TITLE
Unit evaluation in math power function

### ISSUE THREAD

**Issue by jackkandelaars** [mbeddr/mbeddr.core#1854]
I have a problem with the evaluation of the units when using the math power function.
The following units I have defined:
![unit evaluation in math power function 0](https://user-images.githubusercontent.com/35758545/35318961-0ba3b44c-00de-11e8-81d9-e1faf9b6bce8.png)

I use these units in the following  calculation. GetVOut returns a double/mmps/ type. See next figure.
![unit evaluation in math power function 1](https://user-images.githubusercontent.com/35758545/35318963-0f5d4382-00de-11e8-846d-60c90d4e268b.png)

The math pow function returns a double type. See next figure.
![unit evaluation in math power function 2](https://user-images.githubusercontent.com/35758545/35318966-12875098-00de-11e8-8c5a-8ac241809395.png)

The exponent of the power function is an integer so I didn’t expect a double but a double/mm2ps2/ type. See next figure.
![unit evaluation in math power function 3](https://user-images.githubusercontent.com/35758545/35318970-197cadb2-00de-11e8-9ba3-7cca19c69474.png)

I understand that with an floating point exponent you can’t determine the unit of the result but for a integer exponent you would expect an unit result.
Is the above statement correct? If yes can this issue be corrected?

**Comment by krishnanm86** [comment]
#1864

**Comment by alexanderpann** [comment]
Closing because it seems to be fixed in https://github.com/mbeddr/mbeddr.core/pull/1864.
