### ISSUE TITLE
Dataflow not correct with math functions

### ISSUE THREAD

**Issue by jackkandelaars** [mbeddr/mbeddr.core#1855]
I have the following code snippet where a warning is issued that the variable is not used. The variable is used in the frac math expression so I don't expect this warning. The sqrt math expression has the same problem.

![dataflow not correct with math functions 0](https://user-images.githubusercontent.com/35758545/35322071-3d459046-00e9-11e8-99bd-b766d78bbddb.png)

If I use the variable in the regular mbeddr code I don't get this warning.

![dataflow not correct with math functions 1](https://user-images.githubusercontent.com/35758545/35322195-b5e6f72e-00e9-11e8-8925-663488a5a316.png)

**Comment by krishnanm86** [comment]
@jackkandelaars The fix is being reviewed in the following pull request #1871

**Comment by krishnanm86** [comment]
Issue fixed and closed
