### ISSUE TITLE
Enable masking/unmasking of edges in diagrams based on generic box/edge queries

### ISSUE THREAD

**Issue by stephaneberle9** [mbeddr/mbeddr.core#1860]
- Enable selected edge(s) to be hidden, e.g., via right-click on edge + context menu entry
- Enable all hidden edges to be shown again, e.g., via right-clicking on box + context menu entry

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/56)

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/58)
