### ISSUE TITLE
Automatically fit to size all new boxes placed on diagrams

### ISSUE THREAD

**Issue by stephaneberle9** [mbeddr/mbeddr.core#1861]
Sometimes, when new boxes are placed in a diagram, their text becomes very small and is hard to read. The problem can be fixed manually by clicking the *Fit to size* tool botton. But it would be better, if new boxes were automatically fitted to their size as soon as they appear in the diagram

**Comment by stephaneberle9** [comment]
The desired behavior can be achieved by setting allow scaling in the generic box query to false. However, it'd be useful to have false as default value on that setting.

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/57)
