### ISSUE TITLE
Support automatic resizing of diagram pane to make sure that diagram content can be fully seen

### ISSUE THREAD

**Issue by stephaneberle9** [mbeddr/mbeddr.core#1862]
Sometimes ports and/or their tooltips (i.e., port labels) that are located close to the left diagram limit get cut off. The user must move them manually to another location so as to see them fully. It would be helpful if the diagram pane could be automatically extended in such cases so that the diagram content remains fully visible.

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/63)
