### ISSUE TITLE
Bogus warning message when opening MPS with Mbeddr (solution_descriptor macro undefined)

### ISSUE THREAD

**Issue by krishnanm86** [mbeddr/mbeddr.core#1875]
This seems to stem from the spawner jar file having a bogus entry inside its xml which is later used by MPS during modules loading.

Further investigation needed on why the spawner lib folder actually has a jar file to the spawner tool which loads all this jar files from the lib.

**Comment by alexanderpann** [comment]
The debugger was removed in https://github.com/mbeddr/mbeddr.core/pull/2509. The ticket is now obsolete.
