### ISSUE TITLE
Missing information in graphical projection of a composite block

### ISSUE THREAD

**Issue by krishnanm86** [mbeddr/mbeddr.core#1877]
Starting Point
The user creates an incomplete connection in the textual view. This is a point of inconsistency visible to the user in textual projection.

User Action
The user now switches to graphical view.

Result
This user now doesn't see any inconsistency! Though this information is still there, also in the visualization.

Expected Result
Multiple folds:
Graphical projection should be as much as of a lossless projection of the textual/other projections. Units/conversions are pending and need separate issues to address and are beyond the scope of this issue.

![image](https://user-images.githubusercontent.com/2853589/36489907-63250734-1727-11e8-8b0a-0ef367204a1f.png)

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/55)
