### ISSUE TITLE
com.mbeddr.doc: root nodes with same name in same virtual package are overriden

### ISSUE THREAD

**Issue by arimer** [mbeddr/mbeddr.core#1885]
The preprocessing script: <a href = "http://127.0.0.1:63320/node?ref=r%3A716d4aa1-57d8-4a9c-b02d-c1375c64785d%28com.mbeddr.doc.generator.template.main%40generator%29%2F6416473402306272609&project=audi.example">renderCodeScreenshotsAndAttachOutputLocation </a> will ignore and override root nodes with the same name in the same virtual model.

**Comment by coolya** [comment]
This not a bug it is the intended behaviour as the logic in the script has little ways to recover from this situation a previous generator has to ensure this deconfliction.
