### ISSUE TITLE
Concept diagram should work under solutions

### ISSUE THREAD

**Issue by joao-silveira** [mbeddr/mbeddr.core#1895]
Currently concept diagram works only inside a language structure aspect. It should also work inside solutions.

**Comment by danielratiu** [comment]
@joao-silveira this functionality already works (I am using this for documenting parts of ESD) Enabling this was my motivation to work on #1892

**Comment by joao-silveira** [comment]
@danielratiu ok perfect! I wasn't sure if that was enough to make it work under solutions. But if it works I guess we can close this issue.
