### ISSUE TITLE
Action filters are not the applied on the first startup

### ISSUE THREAD

**Issue by joao-silveira** [mbeddr/mbeddr.core#1906]
On the first startup action filters are never applied. It seems to me like the problem is that at the first time there are no persisted profiles, however action filters always tries to apply filters from the persisted model. See:

http://127.0.0.1:63320/node?ref=r%3A029ac95e-aded-47e9-99a5-74435e6e754c%28com.mbeddr.mpsutil.actionsfilter.generator.template.main%40generator%29%2F3912347023913572219

The line I think is causing the problem is exactly the last one where it always tries to load filters from persisted model:
`ActionsApplicationComponent.getInstance().loadState(persistentModel);`

**Comment by arimer** [comment]
Same issue as: #1899

**Comment by joao-silveira** [comment]
To be clear this problem is not just related to the first startup. To make the filters work one must first apply the actions from the settings.

What it is expected is that at the first startup:
1 -  Action filter settings are applied.
2 - Settings are stored in the actionFilters.xml

**Comment by till-f** [comment]
Just verified that this issue was also resolved with the fix of issue #1899
