### ISSUE TITLE
Grammar Cells OptionalCell gives compiler error when using a projection or only a constant cell

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#1909]
If I use this:
![image](https://user-images.githubusercontent.com/6429350/39119541-68b22840-46ec-11e8-9229-959f50e4dc9e.png)
or this:
![image](https://user-images.githubusercontent.com/6429350/39119567-7576f8bc-46ec-11e8-877f-5cb91f7a0ade.png)
or a combination of the two, I get compiler errors.
If I use this:
![image](https://user-images.githubusercontent.com/6429350/39119600-8dae5ba0-46ec-11e8-9c6e-64b225334756.png)
it nicely builds.
Although obvious for people who know it, I think it would be helpful to add a descriptive error message that tells new users that you cannot use a projection or a constant cell only in this case.
For example code, please see attached zip.
[GrammarCellsTest.zip](https://github.com/mbeddr/mbeddr.core/files/1937570/GrammarCellsTest.zip)

**Comment by alexanderpann** [comment]
The generator nowadays shows an explanation that the content of the optional cell is not supported. Checking rules would be nicer but that should be sufficient.
