### ISSUE TITLE
Actionfilters not loading at startup

### ISSUE THREAD

**Issue by krishnanm86** [mbeddr/mbeddr.core#1937]
The custom action filters donot load at startup, but rather require to be "applied" manually in the Setting menu.

**Comment by coolya** [comment]
fixed on a branch will take carte back porting it to master. 

It's fixed in the maintaince branch for MPS 2017.3

**Comment by krishnanm86** [comment]
Actually we need it in milestone/v17.0-1. Is there a commit message to the same?
