### ISSUE TITLE
Coverage of ShortLambdaExpression

### ISSUE THREAD

**Issue by ftomassetti** [mbeddr/mbeddr.core#1938]
I am experiencing issues with the coverage of ShortLambdaExpression. I think it is happening because a copy of the child expression is made in node.makeExplicitLambda(context) and that copy is actually interpreted so the original node is not marked as interpreted, therefore it results uncovered

**Comment by alexanderpann** [comment]
Fixed in https://github.com/IETS3/iets3.opensource/pull/540.
