### ISSUE TITLE
ProjectView: Context menu on virtual folders

### ISSUE THREAD

**Issue by slisson** [mbeddr/mbeddr.core#1953]
Allow to define an action group on virtual folders.

**Comment by slisson** [comment]
A data key is required to give actions access to the selected folder.

**Comment by till-f** [comment]
+1 for this feature!

The mbeddr "New Roots" action group and "Rename" action should be included by default (if no custom action group is provided). For me this is even more important than being able to customize the action group of virtual folders.

**Comment by slisson** [comment]
MPSCommonDataKeys.TREE_NODE can be used with a cast to FolderTreeNode.
