### ISSUE TITLE
Diagram Editor: view of a nested querylist editor is not updated when selecting a reference from completion menu

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#1959]
When a querylist editor is nested in a diagram editor (e.g. in a diagram.box editor), upon selecting an item (e.g. a reference to some other node) from the completion menu, the name of the reference in the diagram editor is not updated visually. The update only happens when you change focus (e.g. de-focus from the cell in which you just changed the value).

Expected behavior would be that the update happens instantaneously and the superfluous focus change is not needed.

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/54)
