### ISSUE TITLE
Diagram Editor: Upon auto-layout, edges get surprising shapes and labels are not correctly repositioned to their respective edges

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#1960]
When using the _auto-layout diagram_ button (![image](https://user-images.githubusercontent.com/6429350/42809863-dcabb89e-89b6-11e8-9daf-12eb4adda615.png)):
 * edges get surprising forms (with all types of unnecessary loops)
 * the labels that belong to these edges do not get positioned along the edge but at seemingly random places (often overlapping other contents), which renders the resulting diagram unreadable.

Pressing the _relayout connected edges_ button (![image](https://user-images.githubusercontent.com/6429350/42810696-d3e2fc3e-89b8-11e8-9218-4ba0716df386.png)) several times improves some of the label positions, but after pressing it many times, a fixpoint is reached that does not yield the correct result (all the initial "strangely shaped" edges still have the same shape and some labels still don't have the correct position).

Expected behavior would be that all edges have consistent, "clean" (without weird loops) shapes and the labels are positioned along the edges.

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/53)
