### ISSUE TITLE
Diagram Editor: Self-to-self edge becomes zero-length and unchangeable

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#1961]
When creating an edge for which the source and target nodes are the same, this edge has length zero and cannot be resized or reshaped manually.

Expected behavior would be that the edge is initially layouted so that it is a clear "self-to-self" edge (e.g. going from the top to the bottom of the "self-box") and that the edge's shape can be adjusted manually.

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/52)
