### ISSUE TITLE
Diagram Editor: Add a "starting box" concept to layout specification in a diagram

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#1963]
Current layout options allow only for specifying tree or layered (with a direction - down, up, left, right). Please add a way to specify a specific node (e.g. by concept or by specific properties) that can serve as a starting point for the layout (i.e. will be used as the most top, left, right, or bottom - depending on the direction chosen in the layout).

An example of a use case for this is a statemachine diagra, where auto-layout should always start with initial states and the positions of other states are automatically layouted based on these initial states.

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/51)
