### ISSUE TITLE
Diagram Editor: Searching for text in a diagram starts renaming elements

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#1964]
When starting a search (Ctrl+F) and typing a search term, after typing exactly 3 characters, a node in the diagram with a textual item that matches the search is selected, the first 3 characters in that textual item are selected and focus is put onto that textual element. 
The result of this is, that when you continue typing, the textual elements gets renamed (i.e. the first three selected characters are replaced by anything that is typed after the jump to the textual element).

Expected behavior would be that the found nodes are highlighted and that the first search result in the diagram is brought into the (center of the) view area (incremental search behavior), but without selecting (part of) the respective textual element.

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/50)
