### ISSUE TITLE
Diagram Editor: print editor button does not produce a result when a diagram is present

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#1965]
When pressing the print editor button (![image](https://user-images.githubusercontent.com/6429350/42813262-a629374c-89c0-11e8-8397-7544997ffa7a.png)) in the toolbar while a diagram editor is present in the current model, no screenshot is created (although the copy/paste buffer contains a path to the file that should have been created).

Expected behavior: screenshot functionality works with diagram editors (ideal scenario, because this is consistent with screenshot-functionality of other editors), or there is an alternative good way of making images of models with a diagram editor in them.

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/49)
