### ISSUE TITLE
Build misses code/plugins

### ISSUE THREAD

**Issue by josefmueller** [mbeddr/mbeddr.core#1989]
Hi,

On line 26 of code/languages/build.xml it requires a path to ${mbeddr.github.core.home}/code/plugins. However, code/plugins does not exist anymore. How it should be fixed to be able to build mbeddr?

Thank you in advance.

**Comment by danielratiu** [comment]
Hi Josef,

mbeddr is built now with gradle - just run "gradlew.bat" from the root
directory.

Dan

**Comment by alexanderpann** [comment]
Closing because of reason mentioned by Daniel.
