### ISSUE TITLE
The "default image path" in DocumentConfig can not be referenced by an ImageParagraph.

### ISSUE THREAD

**Issue by kbirken** [mbeddr/mbeddr.core#1991]
Use case: Embed an image into documentation written with com.mbeddr.doc.

When using the ImageParagraph concept from com.mbeddr.doc, a path for an image file has to be specified (see "from" element). However, it is not possible to reference the path which has been specified as "default image path" in the DocumentConfig.

It is possible though to reference the "temp" path from the DocumentConfig. So currently images can only be provided by storing them into the file system folder referenced by the "temp" path.

**Comment by alexanderpann** [comment]
It looks like it was fixed in #2016.
