### ISSUE TITLE
Images from an ImageParagraph are not shown in HTML output.

### ISSUE THREAD

**Issue by kbirken** [mbeddr/mbeddr.core#1992]
Use case: Embedded an image file into documentation using ImageParagraph and show it as part of the generated html output.

During HTML generation, the image file should be copied to the images-folder inside the doc_gen tree and the reference inside the HTML code should have the proper path. This is how it currently looks like:

```
  <div class="imageWithBorder">
            <img src="doc_temp/CreateVariabilityChunk.png" />
</div>
```

Here, the doc_temp folder right below the solution root has been used as storage location for the image file. However, the generated HTML file is located deep inside the doc_gen folder and thus the relative path is not working.

**Comment by alexanderpann** [comment]
Closing because it seems to be fixed in PR https://github.com/mbeddr/mbeddr.core/pull/2016.
