### ISSUE TITLE
remove slf4j-log4j12 from mpsutil.httpsupport

### ISSUE THREAD

**Issue by KemalSoysal** [mbeddr/mbeddr.core#1993]
When starting up MPS from Code I see following log in the console in IntelliJ Idea
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/..../plugins/com.mbeddr.mpsutil.httpsupport/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/MPSGH/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]

**Comment by alexanderpann** [comment]
The library was removed a long time ago.
