### ISSUE TITLE
CssSpecification should rootable outside of generators

### ISSUE THREAD

**Issue by coolya** [mbeddr/mbeddr.core#2035]
The [CssSpecifications](http://127.0.0.1:63320/node?ref=r%3A25d6e7db-06a4-44ee-83aa-8c5bf17f3b3a%28com.mbeddr.doc.gen_xhtml.structure%29%2F6347396756633822235&project=audi.example) is currently only allowed as a root inside of generators. This makes little sense in case you want to ship a CSS file as part of your normal languages. We should remove the constrains entirely and let the user decide where to place it.

**Comment by alexanderpann** [comment]
Fixed in 446c1d1
