### ISSUE TITLE
com.mbeddr.mpsutil.comparator uses deprecated API

### ISSUE THREAD

**Issue by arimer** [mbeddr/mbeddr.core#2048]
Currently the comparator is using some deprecated API from `SNode` (`getPropertyNames()`) which causes some runtime exception is certain secenarios:

See: 
https://github.com/JetBrains/MPS-extensions/issues/171

**Comment by alexanderpann** [comment]
Closing because it seems to be fixed in https://github.com/mbeddr/mbeddr.core/commit/3f651f9db67a43e9e75b0a00d9d8a584b65b11ef.
