### ISSUE TITLE
com.mbeddr.mpsutil.conceptdiagram: Wrong notation for rendered references 

### ISSUE THREAD

**Issue by arimer** [mbeddr/mbeddr.core#2057]
**Aggregation used for rendering references**
The concept diagram is currently using a wrong presentation for the rendering of references. 
In the example below, a simple cross reference is rendered as an [Aggregation relation](https://en.wikipedia.org/wiki/Object_composition#Aggregation) between two concepts.
<img width="855" alt="grafik" src="https://user-images.githubusercontent.com/16648247/55387084-13798400-5531-11e9-82e9-6b51ac4ae206.png">

**Comment by felixreimann** [comment]
Isn't this correct? According to https://en.wikipedia.org/wiki/Object_composition#UML_notation
* *composition* (filled diamond): strong "has a" relation, i.e., the component ceases to exist if the composition object is deleted. This corresponds to the *child* relation in MPS.
* *aggregation* (unfilled diamond): weak "has a" relation, i.e., the component may outlive the aggregate object. This corresponds to the *references* relation in MPS.

**Comment by eugenschindler** [comment]
@arimer so is it correct? If it is, maybe good to clean up this issue?
