### ISSUE TITLE
plugins dependencies to stub-models not resolved in upstream projects

### ISSUE THREAD

**Issue by arimer** [mbeddr/mbeddr.core#2070]
Currently we have a problem with dependency resolution in upstream projects.

<img width="772" alt="grafik" src="https://user-images.githubusercontent.com/16648247/58207273-ab4e4f80-7ce2-11e9-80d8-0956fd3a4ed6.png">

Whenever a `@stub` model is packaged as part of a language which is loaded as a pluging, dependencies to the packaged stub models cannot be resolved. 
We had a similar problem when migrating [iets3.os](https://github.com/IETS3/iets3.opensource/pull/224) project to 2019.1

CoS:

- [ ] identify all cases in mbeddr platform
- [ ] create solutions for re-packing the required stubs + update build models
- [ ] fix all broken references to priviously used stubs

**Comment by arimer** [comment]
Not sure if this is on purpose no longer supported by MPS, but nevertheless we should move stubs in a stub solution to avoid problems here.

**Comment by arimer** [comment]
Same problem for: `httpserver.plugin`
<img width="379" alt="grafik" src="https://user-images.githubusercontent.com/16648247/58208265-ac807c00-7ce4-11e9-8190-6d3daebb0a63.png">

**Comment by slisson** [comment]
Solution is to mark all individual jars as source and not the lib folder. See https://github.com/JetBrains/MPS-extensions/commit/1d3e653564f9f13b4596106b2394a2aa28c676b8
