### ISSUE TITLE
Typo in "File explorer for module"

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#2072]
Please fix "Terminal" into "File Explorer" in the description text of the following action in mpsutil:
project: MBD_Mogami (C:\repo\MBD_Mogami)
module:  com.mbeddr.mpsutil.genericactions
model:   com.mbeddr.mpsutil.genericactions.plugin
node:    openModuleDirInFileManager [ActionDeclaration] (root)
url:     http://127.0.0.1:63320/node?ref=r%3Af349b2fc-480a-4a50-8b67-cd3b0a6c33b3%28com.mbeddr.mpsutil.genericactions.plugin%29%2F8624890525768079769

It looks quite weird as it is now:
![image](https://user-images.githubusercontent.com/6429350/58345766-6bf63f00-7e59-11e9-86ce-425a2a1d5860.png)

**Comment by alexanderpann** [comment]
Obsolete: It was renamed to File Manager in Module Folder a while ago.
