### ISSUE TITLE
Invalid error when initializing a struct with {0}

### ISSUE THREAD

**Issue by stephaneberle9** [mbeddr/mbeddr.core#2086]
Example:

![image](https://user-images.githubusercontent.com/1942528/61952874-4ef2ff00-afb5-11e9-9cb1-5bf1de6e3bcb.png)

Expected: no error
Actual: Error: array size does not match (expected: 2 was: 1)

**Comment by alexanderpann** [comment]
This issue was fixed a long time ago.
