### ISSUE TITLE
Mbeddr and mbeddr.platform releases gone from github

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#2106]
Since February 25 2019, all relevant assets from mbeddr releases have disappeared (see image below). 
As argued earlier in the related (I think which could be closed) issue #1712, it is very useful to have these artifacts available on github as well, for easier access, like lab sessions, but also for archiving purposes in case build.mbeddr.com would go offline (while github going offline has a much lower probability).

@coolya and @krishnanm86 maybe you can discuss with the team to get this re-enabled if you can agree with my argument?

![image](https://user-images.githubusercontent.com/6429350/67884048-72de5780-fb45-11e9-9a2a-5cbd734b88a8.png)

**Comment by wsafonov** [comment]
I have repaired publishing of mbeddr distribution (there was a memory issue on the build server). Now all usual artefacts will be published as before. However, I haven't really tested the final mbeddr executable - could need some repair too after such a long time. We should address that in a separate ticket and I close this one.
