### ISSUE TITLE
IntegratedCExample in code/applications is not properly migrated

### ISSUE THREAD

**Issue by eugenschindler** [mbeddr/mbeddr.core#2208]
I have donated the IntegratedCExample to code/applications quite a while ago in order to give mbeddr a showcase on how to gradually transform a pure C program into a mixed-DSL program (using statemachines and a local extension to the statemachines, as well as math expressions), showing how that highly reduces the amount of code.
Now it seems that the IntegratedCExample has never been migrated properly through the years.
I have kept migrated code in https://github.com/eugenschindler/mps-mbeddr-intro-course-exercises (including archive branches for MPS versions 2020.1-2021.1) for various courses I co-taught. The relevant part for the fully worked-out IntegratedCExample can be found in the folder Step4-FullSolutionWithMathFormula (https://github.com/eugenschindler/mps-mbeddr-intro-course-exercises/tree/main/Step4-FullSolutionWithMathFormula).
I can do a low-effort step to put the 2021.1-based version back into the mbeddr.core repo so that it is not broken if someone wants it (although I can imagine no-one is interested, since I haven't seen any issues about IntegratedCExample come by - or I have missed them). Just let me know if you want that.

**Comment by alexanderpann** [comment]
We started in MPS 2022.2 to migrate those applications again. They shouldn't be broken anymore but we might miss some non-essential migrations. The applications folder is also part of the [big project task](http://mbeddr.com/mps-platform-docs/mbeddr/big_project/), so hopefully those projects won't be forgotten in the future.
