### ISSUE TITLE
Chunk import scope should contain other chunks inside a NodesTestCase

### ISSUE THREAD

**Issue by kbirken** [mbeddr/mbeddr.core#2223]
When putting two Chunk-like root nodes in a 'NodesTestCase', it should be possible to import one from the other. The scope of the Chunk-import contains chunk root nodes which are located in the model, but not those in the `NodesTestCase`. This is probably a shortcoming of `DefaultGenericChunkDependency`, which is usually being used when deriving a concrete concept from the abstract concept `Chunk`.

Here is an example with KernelF's `Library` from iets3.opensource

<img width="655" alt="image" src="https://user-images.githubusercontent.com/1193045/177505635-346bbf45-e450-47fa-8ac9-879496111204.png">

It should be possible to import `Lib1` from `Lib2` here.

**Comment by alexanderpann** [comment]
Fixed in https://github.com/mbeddr/mbeddr.core/commit/b9171f10b4f5461fdbf90e408c214184709949fd.
