### ISSUE TITLE
mpsutil: Provide language for nodes display control with ICanHide interface

### ISSUE THREAD

**Issue by kbirken** [mbeddr/mbeddr.core#2244]
The visualization of nodes in editors may depend on some logic that is implemented outside the language definition. By providing the `ICanHide` interface, the hiding logic can be delegated to other layers but evaluated in the concept editor where the language is defined. The new interface concept `ICanHide` should be implemented in a new language `com.mbeddr.mpsutil.editor.displayControl`.

Example use case (from IETS3 Variability): 
The preview of nodes in editors may depend on the availability of those nodes according to the selection status in a variability model.
Unselected nodes could be hidden, reducing the cognitive load during artifact analysis.

This ticket has been moved here from IETS3.opensource, see [issue 614](https://github.com/IETS3/iets3.opensource/issues/614).

**Comment by mfsoliveira** [comment]
Closed with PR #2245
