### ISSUE TITLE
com.mbeddr.mpsutil.genericactions.openGeneratorDirInFileManager should skip models without output location

### ISSUE THREAD

**Issue by malueck** [mbeddr/mbeddr.core#2262]
`openGeneratorDirInFileManager` throws a `RuntimeException` if `SModelOperations.getOutputLocation(this.model)` returns null.
But this can easily happen by design if a model has no corresponding facet, see the documentation of SModelOperations:

```
 @return {@code null} if model is not capable to produce output for a model (e.g. deployed/packaged module) 
 @see jetbrains.mps.project.facets.JavaModuleFacet 
 @see jetbrains.mps.project.facets.TestsFacet
```
(MPS 2021.3.2)

The exception is caught without error handling in execute() (fine for me), but it is not caught at all in isApplicable(), which leads to continuous error spamming.

**Comment by alexanderpann** [comment]
Fixed in #2263 in branch maintenance/mps20211. It might take a while until the commits arrive in master, since I just did a cascading merge of all branches a few days ago.
