### ISSUE TITLE
mbeddr.doc: FormattedText nodes cannot be copied/pasted

### ISSUE THREAD

**Issue by kbirken** [mbeddr/mbeddr.core#2400]
Nodes of concept `FormattedText` do not behave properly with cut/copy/paste. _Cut_ does not remove the node and both _cut_ and _copy_ do not put the node into clipboard.

Tested with `\code`, `\emph` and `\bold`, but it probably is the same for all other implementors of `FormattedText`.

**Comment by kbirken** [comment]
I believe this a regression, I remember that it worked earlier (maybe about a year ago).

**Comment by alexanderpann** [comment]
This is a known issue in MPS-Extensions: JetBrains/MPS-extensions#828 that's why I close this issue.
