### ISSUE TITLE
Missing entry in mps-platform-docs for json importer

### ISSUE THREAD

**Issue by arimer** [mbeddr/mbeddr.core#2423]
In mbeddr we support already the feature of [importing json files](http://127.0.0.1:63320/node?ref=r%3A6492a138-3e52-4756-96b0-7e3c330fe78e%28com.mbeddr.mpsutil.json.plugin%29%2F7931153496512862609) or [pasting content of json files](http://127.0.0.1:63320/node?ref=r%3A6492a138-3e52-4756-96b0-7e3c330fe78e%28com.mbeddr.mpsutil.json.plugin%29%2F5524881290247285077) in the contenxt of the `com.mbeddr.mpsutil.json` language. 
However our documentation does not mention those features at the moment. 

See:  http://mbeddr.com/mps-platform-docs/platform_essentials/mpsutils/importer_and_exporter/

**Comment by alexanderpann** [comment]
The documentation was there but I moved it to the importer and exporter page.
