### ISSUE TITLE
Collapsing an annotated child temporarily freezes editor

### ISSUE THREAD

**Issue by Viitrexx** [mbeddr/mbeddr.core#2494]
When using `com.mbeddr.mpsutil.review.structure.ReviewNote` in combination with `de.itemis.editor.collapsible.CellModel_Collapsible`, collapsing a list of nodes results in some editor issues if one of the children has an annotation.

1. The editor freezes until I hit F5 or manage to edit something that forces a refresh (e.g. the name).
2. When collapsed, the annotation floats around at the top without a  clear connection to the hidden child.

![image](https://github.com/user-attachments/assets/73c5777b-124a-4ebc-877e-77a63c20abe8)

```
JetBrains MPS 2022.2.2
Build #MPS-222.4554.1547, built on December 13, 2023
Runtime version: 17.0.8.1+7-b1000.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry:
    freeze.reporter.enabled=false
    idea.invalidate.caches.invalidates.vfs=true

com.mbeddr.mpsutil.margincell_review: bundled 2022.2-2022.2.24670.e29e3e9
```

**Comment by alexanderpann** [comment]
Fixed in 2022.2.24850.9ed13dd for your use case. Please reopen if you run into any other problems.
