### ISSUE TITLE
Typessystem error when casting empty types with unit

### ISSUE THREAD

**Issue by bkolb** [mbeddr/mbeddr.core#652]
example

int16/C/ temp1 = 10 C; 

((int16) (temp1 / temp1));

int16 is underlined with the following message: Error: type int16 is not a subtype of int16/[]

We have an ineqReplacement rule which should actually handle this case but somehow does not (replaceEmptyUnitTypeWithBaseType)

Any idea?

**Comment by alexanderpann** [comment]
This seems to be working nowadays.
