### ISSUE TITLE
Replace LOOP+TRACE with LOOP_T

### ISSUE THREAD

**Issue by DomenikP** [mbeddr/mbeddr.core#662]
The LOOP macro does not create tracing information. Therefore, MPS provides the TRACE macro which writes tracing information for a single node. To enable traces for nodes inside the LOOP, we put a TRACE macro directly below the LOOP. However, this blows up the generator and decreases readability (see image below).

![bildschirmfoto 2013-03-06 um 12 02 08](https://f.cloud.github.com/assets/971504/636606/ef676c48-d288-11e2-83d2-904b8945678e.png)

In order to improve the readability, we create a new language concept LOOP_T (reduced to a LOOP+TRACE) and use it where necessary.

**Comment by alexanderpann** [comment]
The debugger was removed in https://github.com/mbeddr/mbeddr.core/pull/2509. The ticket is now obsolete.
