### ISSUE TITLE
Debugging Code with static Variability

### ISSUE THREAD

**Issue by DomenikP** [mbeddr/mbeddr.core#708]
The current debugger implementation operates on the AST and considers each mbeddr statement has a representation in the generated C code. However, when using static variability, variables, functions, statements etc. don't need to have a C representation, if they are part of another configuration that is not part of the binary.

**Comment by alexanderpann** [comment]
The debugger was removed in https://github.com/mbeddr/mbeddr.core/pull/2509. The ticket is now obsolete.
