### ISSUE TITLE
Stepping Support for StatemachineTestStatement

### ISSUE THREAD

**Issue by DomenikP** [mbeddr/mbeddr.core#722]
During the migration we implemented ISteppable in StatemachineTestStep due to a broken reference in StatemachineTestStatement's behavior.
Stepping on these conceots should be validated after the migration is finished.

**Comment by alexanderpann** [comment]
The debugger was removed in https://github.com/mbeddr/mbeddr.core/pull/2509. The ticket is now obsolete.
