### ISSUE TITLE
Add logging capability to assert statements

### ISSUE THREAD

**Issue by stephaneberle9** [mbeddr/mbeddr.core#799]
In case of test failures it would be convenient if one could output complementary information on the console. Right now I have to implement a somewhat ugly workaround to achieve this, e.g.:

assert(0) energyData.phases[0].readings.reactivePower == 0 cVar; 
if (energyData.phases[0].readings.reactivePower != 0 cVar) { 
  printf("%3.0f;...\n", simulationParameters.nominalRMSVoltage, ...)
} if

It would be cool if one could embed the printf statement right into the assert statement, i.e., in a similar way as it is possible to specify on/if conditions in report statements.

**Comment by coolya** [comment]
Asserts now print the expected and actual value to the console and the `.asserts` file.
