### ISSUE TITLE
Win installer, Java & Cygwin

### ISSUE THREAD

**Issue by franz-josef-kaiser** [mbeddr/mbeddr.core#879]
I just downloaded and installed the windows installer for 3.0.1 EAP. It detects Java as not installed (I got Java installed) and then tries to download Cygwin (which I as well already got installed).

It would be nice to be able to opt out ("Java is installed - configure later") of the Java isntall in a more easy way than hitting _Cancel_ and _Cancel_ several times until the installer magically just skips that part and continues to install.

The same goes for Cygwin. Being able to just state that it is already installed would be more than a feature. I'm developing software (PHP, JS) and I really don't want to have a second instance installed and surely don't want to have my currently existing install either deleted or getting reconfigured by an external software package.

As nice as it sounds to have a software doing configuration on the fly and taking this "burden" off a users shoulders, I really prefer just having a solid explanation what configuration tasks have to be done. This (like any other) software doesn't get installed on a vanilla computer :)

Thanks!

**Comment by coolya** [comment]
We now ship java and have a new installer
