### ISSUE TITLE
when port connected does not work for multiplicity-many required ports

### ISSUE THREAD

**Issue by stephaneberle9** [mbeddr/mbeddr.core#988]
Example:

component SomeImpl {
  requires ISomething something [0..2]

  void someRunnable() {
    when port connected (something) {
      ...
    }
  }
}

Generated C code:

if ( ___castedInstanceData->port_something != 0 ) {
  ...
}

Expected C code: 

Some kind of loop the runs over the port_something void\* array and tests if any of its entries is not null.

**Comment by muehlbrandt** [comment]
If I enter
```
when port connected( portname[index] ) {
 ...
}
```
the generated code misses the index:
```
if ( ___cid->componentName__portname != NULL ) {
...
} 
```

 As a result the null check does not work as intended.
